### PR TITLE
fix(serializer): use data if no uri_variables provided

### LINKED ISSUE #5736: PR #5604 breaks operations on subresources for PUT operation on Resource when placeholders are named differently than "id"
**API Platform version(s) affected**: 3.1.13

**Description**  
With PR #5546, was introduced the ability to operate on subresources also if the placeholders of the IDs are not named "id".

The PR #5604 actually breaks this feature.

If placeholders are named "id", the code continues to work as there is a fallback in `ItemNormalizer` that returns `$data['id']` if the key `uri_variables` is not set in the `$context`:

https://github.com/api-platform/core/blob/92a81f024541054b9322e7457b75c721261e14e0/src/Serializer/ItemNormalizer.php#L87-L91

But, as the key `uri_variables` is now always removed, the method `ItemNormalizer::getContextUriVariables()` never works as it should.

The PR #5604 was published due to those issues:

- https://github.com/api-platform/core/issues/5587
- https://github.com/api-platform/core/issues/5603

**Reading them behind the lines, they are originates from the same problem: both the Resource and the SubResource have the placeholder named "id".**

This causes the confusion in `ItemNormalizer` that uses the wrong "id" key to retrieve the SubResource.

**How to reproduce**

Create two resources, for example Alpha and Beta
Create a field in Beta which is a relation to Alpha
Try to create/update Beta

**Working on 3.1.12 | NOT working on 3.1.13**

```
PATCH /betas/{beta_id}
{
  "alpha": "/alphas/{alpha_id}"
}
```

**NOT Working on 3.1.12 | (Now) Working on 3.1.13**

```
PATCH /betas/{id}
{
  "alpha": "/alphas/{id}"
}
```

**Possible Solution**  

https://github.com/api-platform/core/pull/5739

### PR DESCRIPTION
**Pull request by soyuka**
fixes #5736

### CODE REVIEW

File: src/Serializer/ItemNormalizer.php [hunk 1]
```diff
@@ -86,11 +86,7 @@ private function updateObjectToPopulate(array $data, array &$context): void
 
     private function getContextUriVariables(array $data, $operation, array $context): array
     {
-        if (!isset($context['uri_variables'])) {
-            return ['id' => $data['id']];
-        }
-
-        $uriVariables = $context['uri_variables'];
+        $uriVariables = $context['uri_variables'] ?? $data;
```
Comment (soyuka) [inline src/Serializer/ItemNormalizer.php:89]: @Aerendir can you try this?

File: features/main/patch.feature [hunk 2]
```diff
@@ -58,3 +58,26 @@ Feature: Sending PATCH requets
...
+    And the JSON should be equal to:
+    """
+    {
+      "@context": "/contexts/Beta",
+      "@id": "/betas/1",
+      "@type": "Beta",
+      "betaId": 1,
+      "alpha": "/alphas/2"
+    }
+    """
```
Comment (soyuka) [inline features/main/patch.feature:83]: @Aerendir this works right now so I'm not sure what the issue is, are you using merge-patch?

File: src/Serializer/AbstractItemNormalizer.php [hunk 3]
```diff
@@ -899,4 +877,28 @@ private function setValue(object $object, string $attributeName, mixed $value):
...
+            unset($context['operation'], $context['operation_name']);
+            $context['resource_class'] = $resourceClass;
+            if ($this->resourceMetadataCollectionFactory) {
+                $context['operation'] = $this->resourceMetadataCollectionFactory->create($resourceClass)->getOperation();
+                $context['operation_name'] = $context['operation']?->getName();
+            }
+        }
+
+        return $context;
+    }
```
Comment (soyuka) [inline src/Serializer/AbstractItemNormalizer.php:903]: @jonag can you try this and use `root_operation`?

Comment (jonag) [reply src/Serializer/AbstractItemNormalizer.php:910]: Updating to API Platform v3.1.14 and changing my custom normalizer to use the root_operation instead of the operation fixes all my tests! 
Thank you 👏!

File: src/Serializer/ItemNormalizer.php (hunk 1 above)
Comment (Aerendir) [reply src/Serializer/ItemNormalizer.php:89]: Hi @soyuka , I've tried the fix, but it doesn't work...

In `ItemNormalizer::getContextUriVariables()`, there is no key `$context['uri_variables']`, so the variable `$uriVariable` gets the value of `$data`, but `$data` contains the entity and so there will never be the uri variables needed.

I'm going to reproduce in tests what's going on...

File: features/main/patch.feature (hunk 2 above)
Comment (Aerendir) [reply features/main/patch.feature:82]: @soyuka , no, I'm using `PUT`s... I'm going to reproduce the scenario...
