### PR TITLE
Fix #3979 identifier chain not breaking after denormalizing

### LINKED ISSUE #3979: identifier denormalizer does not work anymore with custom needs.
**API Platform version(s) affected**: 2.6.x

**Description**  

This following code inspired by https://gist.github.com/soyuka/c25aa66728439eec56419a5a20295592
does not work anymore with 2.6.0 and 2.6.1.

```
<?php

declare(strict_types=1);

namespace App\Identifier;

use Monofony\Contracts\Core\Model\User\AppUserInterface;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;

final class AppUserIdentifierNormalizer implements DenormalizerInterface
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    /**
     * {@inheritdoc}
     *
     * @psalm-suppress InvalidReturnType
     * @psalm-suppress InvalidReturnStatement
     */
    public function denormalize($data, $type, $format = null, array $context = [])
    {
        $user = $this->security->getUser();

        if (null === $user || !$user instanceof AppUserInterface) {
            throw new AccessDeniedHttpException();
        }

        return (string) $user->getCustomer()->getId();
    }

    /**
     * {@inheritdoc}
     */
    public function supportsDenormalization($data, $type, $format = null)
    {
        return 'me' === $data;
    }
}
```
**How to reproduce**  

**Possible Solution**  

**Additional Context**

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3979 
| License       | MIT
| Doc PR        | na

- lower priority of our identifier denormalizer for better DX
- break the chain of normalizers when an identifier transformer is found

### CODE REVIEW

File: src/Identifier/IdentifierConverter.php [hunk 1]
```diff
@@ -69,6 +69,7 @@ public function convert($data, string $class, array $context = []): array
 
                 try {
                     $identifiers[$identifier] = $identifierTransformer->denormalize($value, $type);
+                    break;
                 } catch (InvalidIdentifierException $e) {
                     throw new InvalidIdentifierException(sprintf('Identifier "%s" could not be denormalized.', $identifier), $e->getCode(), $e);
                 }
```
Comment (soyuka) [inline src/Identifier/IdentifierConverter.php:75]: add test
