### PR TITLE
fix(symfony): prevent symfony name converter service pollution

### LINKED ISSUE #7552: `api_platform.name_converter` is applied to Symfony serializer default
**API Platform version(s) affected**: 4.2.6

**Description**  
Hi @soyuka, I feel like the issue https://github.com/api-platform/core/issues/6101 is not totally resolved.

When I set 
```
api_platform.name_converter: serializer.name_converter.camel_case_to_snake_case
```
it still use snake case for the default serializer, even if I use it in a non-api-platform context.

I would expect the config api_platform.name_converter to only impact api platform.
Currenly it basically conflict with the `framework.serializer.name_converter` option...

Which means that if other bundles (like symfony/ai in my case) uses the default serializer, it's impacted by the api_platform config !

**How to reproduce**  
- Set `api_platform.name_converter: serializer.name_converter.camel_case_to_snake_case`
- Use the default serializer somewhere else
- it will use snake case instead of default behavior

**Possible Solution**  
Maybe named serializers could be used to defined a specific serializer for api_platform ?
https://symfony.com/doc/current/serializer.html#named-serializers
Or maybe, rather than provider a name_converter option, it would be better to have a serializer option ?

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Closes #7552 
| License       | MIT
| Doc PR        | na

### CODE REVIEW

File: tests/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php [hunk 1]
```diff
@@ -15,20 +15,18 @@
...
 use Symfony\Component\DependencyInjection\Definition;
 use Symfony\Component\DependencyInjection\Reference;
+use Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter;
 
 /**
  * @author Antoine Bluchet <soyuka@gmail.com>
  */
 class MetadataAwareNameConverterPassTest extends TestCase
 {
-    use ProphecyTrait;
```
Comment (VincentLanglet) [inline tests/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php:30]: Do you plan to remove prophecy ?

Comment (soyuka) [reply tests/Symfony/Bundle/DependencyInjection/Compiler/MetadataAwareNameConverterPassTest.php:30]: ideally yes at some point, whenever I add new tests I prefer avoiding it, I think I wrote that in the CONTRIBUTING.md file

**Comment by VincentLanglet** [comment]
Can we merge this ? :)

**Comment by mbeccati** [comment]
Thanks @soyuka for addressing this. I currently have no means to test, but how does it work in terms of BC?

**Comment by soyuka** [comment]
To me BC should be covered as users configure the name converter through a configuration. Do you have something in mind that I may not have thought of?

**Comment by mbeccati** [comment]
@soyuka My most recent project has no name converter in `package/api_platform.yaml` and:
```
    serializer:
        name_converter: 'serializer.name_converter.camel_case_to_snake_case'

        named_serializers:
            ....
```

So that the default serializer is API Platform's, and it is using the camel_to_snake converter. How would that work after the PR?

**Comment by VincentLanglet** [comment]
I think
```
api_platform:
     name_converter: 'serializer.name_converter.camel_case_to_snake_case'
```
was the right way to override the name converter for ApiPlatform.

**Comment by mbeccati** [comment]
@VincentLanglet which was known to have the side effect of being applied to all the serializers in symfony, until fixed to only affect the default one.

Long story short. In my current projects, I'd like to have API Platform use the default Symfony serializer with the name converter applied and I was wondering if that is still possible after the change and how.

**Comment by VincentLanglet** [comment]
> @VincentLanglet which was known to have the side effect of being applied to all the serializers in symfony, until fixed to only affect the default one.

And now it's fixed to not affect any of Symfony ones since they should be unrelated.

I kinda feel like you were using a hack to avoid a bug and then complaining that the bug is fixed
https://xkcd.com/1172/

> Long story short. In my current projects, I'd like to have API Platform use the default Symfony serializer with the name converter applied and I was wondering if that is still possible after the change and how.

Since the default serializer name converter has a service_id, you can just update the conf to
```
api_platform:
     name_converter: default_serializer_service_id
```
And by the way, this can already be done this way on previous ApiPlatform, which was the documented way.

**Comment by mbeccati** [comment]
What you legitimately see as a bug fix to me is a behaviour change towards a cleaner implementation, which is perfectly fine. Even welcome I would add.

The upgrade would however break application expecting API Platform's "modified" Serializer being injected by default, which is not the case anymore. Documenting it as BC would seem a nice thing to do, if that's the case.

But it could be worse. For example I have updated to 4.2.x-dev and quickly found out that input DTOs are broken unless I manually configure symfony's default serializer with the same name converter. Is that my mistake?

**Comment by VincentLanglet** [comment]
> What you legitimately see as a bug fix to me is a behaviour change towards a cleaner implementation, which is perfectly fine. Even welcome I would add.
> The upgrade would however break application expecting API Platform's "modified" Serializer being injected by default, which is not the case anymore. Documenting it as BC would seem a nice thing to do, if that's the case.

Sure, that's a classic issue with bugfix. It's always a BC break for someone relying on the bug.
But still it's a good idea to document the release about the behavior.

> But it could be worse. For example I have updated to 4.2.x-dev and quickly found out that input DTOs are broken unless I manually configure symfony's default serializer with the same name converter. Is that my mistake?

I don't think it's wanted ; and it's surprising based on the fact (I assume) there are tests about such behavior in API platform.
Do you mind sharing the config of both api platform and symfony serializer ?
Maybe it would be best to discuss about this in an issue ?

**Comment by soyuka** [comment]
Damn I didn't thought someone would do it like this, indeed the name converter should be put on the `api_platform` node I'll add a note to the CHANGELOG! This has not been tagged yet though.
