### PR TITLE
fix(jsonld): reset gen_id configuration

### LINKED ISSUE #7258: BC Breaks
**API Platform version(s) affected**: 4.1.17

**Description**  
Not sure when and where, but now some tests fail:

```
--- Expected
+++ Actual
@@ @@
         '@type' => 'CompanyLeadPreference'
         'industries' => Array (
-            0 => '/api/industries/01936891-9...'
+            0 => 'http://localhost/api/industries/01936891-9...'
         )
         'markets' => Array (
-            0 => '/api/markets/01934ee1-5083...'
+            0 => 'http://localhost/api/markets/01934ee1-5083...'
         )
```

Here we have an intermediate resource which is not api resource, but the skill resource has apiresource definition:
```
--- Expected
+++ Actual
@@ @@
        
             '@type' => 'CompanySkill'
             'skill' => Array (
                 '@type' => 'Skill'
-                '@id' => '/api/skills/01935232-6f05-7e2...fe23e1'
                 'id' => '01935232-6f05-7e2e-b4f6-943d3dfe23e1'

```

and not sure about this:
```
Failed asserting that '{\n
    "@context": "/api/contexts/Error",\n
    "@id": "/api/errors/403",\n
    "@type": "hydra:Error",\n
    "title": "An error occurred",\n
    "detail": "Access Denied. The user doesn't have ROLE_ADMIN.",\n
    "status": 403,\n
    "type": "/errors/403",\n
    "description": "Access Denied. The user doesn't have ROLE_ADMIN.",\n
    "hydra:description": "Access Denied. The user doesn't have ROLE_ADMIN.",\n
    "hydra:title": "An error occurred"\n
}' matches JSON string "{
  "@context": "/api/contexts/Error",
  "@id": "/api/errors/403",
  "@type": "hydra:Error",
  "title": "An error occurred",
  "description": "Access Denied.",
  "detail": "Access Denied.",
  "status": 403,
  "type": "/errors/403",
  "hydra:title": "An error occurred",
  "hydra:description": "Access Denied."
}".
```

**How to reproduce**  

**Possible Solution**  

**Additional Context**

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Tickets       | Closes #7258 #7261
| License       | MIT

I failed reproducing the users bc breaks, I think I isolated the behavior though, @norkunas @GSadee may you please check this patch and tell me if it solves your issues? Also would it be possible to have a look at my test fixtures and let me know how your configuration differs from my test?

### CODE REVIEW

File: src/JsonLd/Serializer/ItemNormalizer.php [hunk 1]
```diff
@@ -124,7 +124,8 @@ public function normalize(mixed $object, ?string $format = null, array $context
             unset($context['operation'], $context['operation_name']);
         }
 
-        if (true === ($context['output']['gen_id'] ?? true) && true === ($context['force_iri_generation'] ?? true) && $iri = $this->iriConverter->getIriFromResource($object, UrlGeneratorInterface::ABS_PATH, $context['operation'] ?? null, $context)) {
+        $operation = $context['operation'] ?? null;
+        if (true === ($context['output']['gen_id'] ?? true) && true === ($context['force_iri_generation'] ?? true) && $iri = $this->iriConverter->getIriFromResource($object, $operation?->getUrlGenerationStrategy() ?? UrlGeneratorInterface::ABS_PATH, $operation, $context)) {
```
Comment (soyuka) [inline src/JsonLd/Serializer/ItemNormalizer.php:128]: this is probably not a necessary patch but it's probably better then the previous code

File: src/Serializer/OperationContextTrait.php [hunk 2]
```diff
@@ -34,7 +34,7 @@ protected function createOperationContext(array $context, ?string $resourceClass
             $context['root_operation_name'] = $context['operation_name'] ?? $context['graphql_operation_name'];
         }
 
-        unset($context['iri'], $context['uri_variables'], $context['item_uri_template'], $context['force_resource_class']);
+        unset($context['iri'], $context['uri_variables'], $context['item_uri_template'], $context['force_resource_class'], $context['output']['gen_id']);
```
Comment (soyuka) [inline src/Serializer/OperationContextTrait.php:37]: this should probably reset the `gen_id` context between child context generation

**Comment by soyuka** [comment]
Didn't meant to merge this, its back at https://github.com/api-platform/core/pull/7264
