### PR TITLE
fix(state): use exception message for user-facing violation when available

### LINKED ISSUE #7893: Support Symfony 8.1 BackendEnumDenormalizer new error
**API Platform version(s) affected**: x.y.z

**Description**
**Symfony PR [#62574](https://github.com/symfony/symfony/pull/62574)** (commit [`35b1aec`](https://github.com/symfony/serializer/commit/35b1aec9e9bbb305a9d632327d05dfc4aeb1164f)) improves `BackedEnumNormalizer` error messages. This change was:
1. Merged to **8.1** branch (Dec 2025)
2. **Accidentally cherry-picked into 8.0.5** — which broke this demo (see [PR #587 comment](https://github.com/api-platform/demo/pull/587#discussion_r2761020763))
3. **Reworked in 8.0.6** (commit `388c311`) — the `expectedTypes = null` behavior was removed from 8.0.x
4. The demo jumped from **v8.0.4 → v8.0.7**, skipping the broken v8.0.5

On the current **Symfony 8.1 branch**, `BackedEnumNormalizer` distinguishes:
- **Type mismatch** (TypeError): `expectedTypes = [$backingType]`
- **Invalid value** (ValueError): `expectedTypes = ['int', 'string']`, message = `"The data must belong to a backed enumeration of type $type"`

**How to reproduce**
Symfony has modified its behavior for BackendEnumDenormalizer in Symfony 8.1. This change is not supported by API Platform and may cause troubles on later migration.
Reproducer: https://github.com/api-platform/demo/pull/617

**Possible Solution**
Support both Symfony 8.0 and 8.1 behaviors.

**Additional Context**
PR in progress...

### PR DESCRIPTION
**Pull request by vincentchalamon**
When a NotNormalizableValueException has canUseMessageForUser() = true, use its message directly as the constraint violation message instead of the generic Type constraint message. This fixes issues with Symfony 8.x where expectedTypes can be null/empty, producing broken messages.

| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Tickets       | Closes #7893
| License       | MIT
| Doc PR        | N/A

### CODE REVIEW

**Comment by soyuka** [comment]
thanks!

**Comment by norkunas** [comment]
The whole point of this IIRC was to use explicitly the same message that the validator would return. Now it's a BC break and will need to fix our testsuite

**Comment by soyuka** [comment]
its not released yet we can rollback, I thought that the `$exception->canUseMessageForUser()` would be a good guard for the BC but maybe that we should discuss this more? 

WDYT @vincentchalamon ? 

It looks like this is fixing a bug for 8.1 and shouldn't impact actual behavior no @norkunas can you give more details? maybe we're missing a regression test?

File: tests/Functional/ValidationTest.php [hunk 1]
```diff
@@ -85,7 +85,7 @@ public function testPostWithDenormalizationErrorsCollected(): void
 
         $violationBaz = $findViolation('baz');
         $this->assertNotNull($violationBaz, 'Violation for "baz" not found.');
-        $this->assertSame('This value should be of type string.', $violationBaz['message']);
+        $this->assertSame('Failed to create object because the class misses the "baz" property.', $violationBaz['message']);
```
Comment (soyuka) [inline tests/Functional/ValidationTest.php:88]: these should not change to preserve BC I guess

Comment (norkunas) [reply tests/Functional/ValidationTest.php:88]: yup, this is what i was refering to.

Comment (soyuka) [reply tests/Functional/ValidationTest.php:88]: though the new messages are way clearer... in 8.1 this breaks and we get "This value should be of type ." not sure how to fix this properly. Isn't that not covered by BC anyways (https://symfony.com/doc/current/contributing/code/bc.html#using-our-translations) ?
