### PR TITLE
[Laravel] Fix GraphQL Resolver Discovery

### LINKED ISSUE #6854: [Laravel] Tagged item resolvers are not registered.
**API Platform version(s) affected**: 4.x

**Description**  
For custom graphql resolvers, there is 2 options:

1. Via the config setting `graphql.resolver`
2. Via tagging ([docs](https://api-platform.com/docs/core/graphql/#custom-queries-config-for-laravel))

However tags are currently not seem to take into account.

**Possible Solution**  
Merge resolvers which are tagged to the resolverprovider inside the API Platform Service Provider

### PR DESCRIPTION
**Pull request by toitzi**
| Q             | A
| ------------- | ---
| Branch?       | 4.x
| Tickets       | Closes #6854
| License       | MIT
| Doc PR        | -

### CODE REVIEW

File: src/Laravel/ApiPlatformProvider.php [hunk 1]
```diff
@@ -1193,10 +1195,12 @@ private function registerGraphQl(Application $app): void
 
         $app->singleton(ResolverProvider::class, function (Application $app) {
             $resolvers = iterator_to_array($app->tagged('api_platform.graphql.resolver'));
+            $taggedItemResolvers = iterator_to_array($app->tagged(QueryItemResolverInterface::class));
+            $taggedCollectionResolvers = iterator_to_array($app->tagged(QueryCollectionResolverInterface::class));
 
             return new ResolverProvider(
                 $app->make(GraphQlReadProvider::class),
-                new ServiceLocator($resolvers),
+                new ServiceLocator([...$resolvers, ...$taggedItemResolvers, ...$taggedCollectionResolvers]),
```
Comment (soyuka) [inline src/Laravel/ApiPlatformProvider.php:1203]: Note that we recommend to use state providers instead of resolvers for most usages.

**Comment by soyuka** [comment]
Thanks @toitzi !
