### PR TITLE
fix(state): do not expose FQCN in DeserializeProvider on PartialDenormalizationException

### LINKED ISSUE #7149: Resource not found during denormalization exposes resource FQCN
**API Platform version(s) affected**: 4.1.8

**Description**  
After PR #6985 was merged, if IRI reference is not found during denormalization, the error message exposes FQCN of the resource class. The error also implies that the IRI is not valid when in fact the resource is just not found.

**How to reproduce**  
Simplified example of the resources
```php
// src/ApiResource/PaymentResource.php
#[ApiResource(
    operations: [
        new Put(
            uriTemplate: '/payments/{uuid}/redeem_voucher',
            input: VoucherRedeemRequest::class,
            processor: VoucherRedeemProcessor::class,
        )
    ]
)]
class PaymentResource {
}

// src/ApiResource/VoucherResource.php
#[ApiResource]
class VoucherResource
{
    public function __construct(
        #[ApiProperty(identifier: true)]
        public string $code,
    ) {
    }
}

// src/ApiResource/VoucherRedeemRequest.php
class VoucherRedeemRequest
{
    public function __construct(
        #[NotBlank]
        #[ApiProperty(readableLink: false, writableLink: false)]
        public readonly ?VoucherResource $code = null,
    ) {
    }
}
```

If you call PUT /payments/{uuid}/redeem_voucher with valid IRI syntax but resource is not found, you get the following error

```
curl -X 'PUT' \
  'https://localhost/payments/e7dcf723-0f27-46f3-b47e-0518616662f2/redeem_voucher' \
  -H 'accept: application/ld+json' \
  -H 'Content-Type: application/ld+json' \
  -d '{"code": "/vouchers/doesnotexist"}'

{
  "@context": "/contexts/ConstraintViolation",
  "@id": "/validation_errors/ba785a8c-82cb-4283-967c-3cf342181b40",
  "@type": "ConstraintViolation",
  "status": 422,
  "violations": [
    {
      "propertyPath": "code",
      "message": "This value should be of type App\\ApiResource\\VoucherResource.",
      "code": "ba785a8c-82cb-4283-967c-3cf342181b40",
      "hint": "The type of the \"App\\ApiResource\\VoucherResource\" resource \"string\" (IRI), \"string\" given."
    }
  ],
  "detail": "code: This value should be of type App\\ApiResource\\VoucherResource.",
  "description": "code: This value should be of type App\\ApiResource\\VoucherResource.",
  "type": "/validation_errors/ba785a8c-82cb-4283-967c-3cf342181b40",
  "title": "An error occurred"
}
```

I think it is preferable not to expose class names and instead message should be simply "_Resource not found._" or maybe "_This value should be of type VoucherResource._" if IRI syntax is not valid.

**Possible Solution**  

**Additional Context**

### PR DESCRIPTION
**Pull request by alexndlm**
| Q             | A
| ------------- | ---
| Branch?       | 4.1
| Tickets       | Closes #7149
| License       | MIT
| Doc PR        | 

Also relates to https://github.com/api-platform/core/pull/6761/files

### CODE REVIEW

File: src/State/Provider/DeserializeProvider.php [hunk 1]
```diff
@@ -36,6 +37,7 @@ public function __construct(
         private readonly ?ProviderInterface $decorated,
         private readonly SerializerInterface $serializer,
         private readonly SerializerContextBuilderInterface $serializerContextBuilder,
+        private readonly ResourceMetadataCollectionFactoryInterface $resourceMetadataCollectionFactory,
```
Comment (soyuka) [inline src/State/Provider/DeserializeProvider.php:40]: It bothers me that we need to inject this but I guess there's no other solution unless we only use reflection?

File: src/State/Provider/DeserializeProvider.php [hunk 2]
```diff
@@ -114,4 +117,30 @@ public function provide(Operation $operation, array $uriVariables = [], array $c
...
+    private function normalizeExpectedTypes(?array $expectedTypes = null): array
+    {
+        $normalizedTypes = [];
+
+        foreach ($expectedTypes ?? [] as $expectedType) {
+            $normalizedType = $expectedType;
+
+            if (class_exists($expectedType) || interface_exists($expectedType)) {
+                try {
+                    $normalizedType = $this->resourceMetadataCollectionFactory->create($expectedType)->getOperation()->getShortName();
```
Comment (soyuka) [inline src/State/Provider/DeserializeProvider.php:130]:
```suggestion
                    $normalizedType = $this->resourceMetadataCollectionFactory->create($expectedType)->getOperation()?->getShortName();
```

File: src/State/Provider/DeserializeProvider.php [hunk 3]
```diff
@@ -114,4 +117,30 @@ public function provide(Operation $operation, array $uriVariables = [], array $c
...
+                } catch (\Throwable) {
```
Comment (soyuka) [inline src/State/Provider/DeserializeProvider.php:131]:
```suggestion
                } catch (OperationNotFoundException) {
```

File: src/State/Provider/DeserializeProvider.php [hunk 4]
```diff
@@ -114,4 +117,30 @@ public function provide(Operation $operation, array $uriVariables = [], array $c
...
+                    // Do nothing
+                }
+
+                if (null === $normalizedType) {
+                    $classReflection = new \ReflectionClass($expectedType);
+                    $normalizedType = $classReflection->getShortName();
+                }
```
Comment (soyuka) [inline src/State/Provider/DeserializeProvider.php:138]: I think this is quite sufficient actually (I thought we could re-use the current `operation` in the normalizers/denormalizers) but indeed in that case the type may be another one then the current operation's one...

**Review by soyuka — CHANGES_REQUESTED** [review]

File: src/State/Provider/DeserializeProvider.php (hunk 2 above)
Comment (alexndlm) [reply src/State/Provider/DeserializeProvider.php:130]: I have checked `\ApiPlatform\Metadata\Resource\ResourceMetadataCollection::getOperation`, it always returns `Operation`.

File: src/State/Provider/DeserializeProvider.php (hunk 1 above)
Comment (alexndlm) [reply src/State/Provider/DeserializeProvider.php:40]: Yes, if we want to use a short name, we need this service.

I would leave only a reflection, for simplicity. However, I can't assess how well it meets the general concept of the API Platform.

File: src/State/Provider/DeserializeProvider.php (hunk 3 above)
Comment (alexndlm) [reply src/State/Provider/DeserializeProvider.php:131]: Thanks

File: src/State/Provider/DeserializeProvider.php (hunk 4 above)
Comment (alexndlm) [reply src/State/Provider/DeserializeProvider.php:138]: Yes, we should fetch the operation exactly for class in `$expectedType`.
