### PR TITLE
Fix #3844 open api shows with jsonld normalizer

### LINKED ISSUE #3844: jsonld.SyntaxError: Invalid JSON-LD syntax; @context term values must be strings or objects
**API Platform version(s) affected**: dev-master

**Description**  
Upgrading from 176cdf9 to dev-master causes an error in React Admin `jsonld.SyntaxError: Invalid JSON-LD syntax; @context term values must be strings or objects`

**How to reproduce**  

For me the call to /api/docs.jsonld changes between versions
176cdf9:
```
{
   "@context":{
      "@vocab":"https:\/\/localhost:8443\/api\/docs.jsonld#",
      "hydra":"http:\/\/www.w3.org\/ns\/hydra\/core#",
      "rdf":"http:\/\/www.w3.org\/1999\/02\/22-rdf-syntax-ns#",
      "rdfs":"http:\/\/www.w3.org\/2000\/01\/rdf-schema#",
      "xmls":"http:\/\/www.w3.org\/2001\/XMLSchema#",
      "owl":"http:\/\/www.w3.org\/2002\/07\/owl#",
      "schema":"http:\/\/schema.org\/",
      "domain":{
         "@id":"rdfs:domain",
         "@type":"@id"
      },
      "range":{
         "@id":"rdfs:range",
         "@type":"@id"
      },
      "subClassOf":{
         "@id":"rdfs:subClassOf",
         "@type":"@id"
      },
      "expects":{
         "@id":"hydra:expects",
         "@type":"@id"
      },
      "returns":{
         "@id":"hydra:returns",
         "@type":"@id"
      }
   },
   "@id":"\/api\/docs.jsonld",
   "@type":"hydra:ApiDocumentation",
   "hydra:title":"Homewerk.co API",
   "hydra:entrypoint":"\/api",
```
compared to dev-master:
```
{
   "@context":{
      "@vocab":"https:\/\/localhost:8443\/api\/docs.jsonld#",
      "hydra":"http:\/\/www.w3.org\/ns\/hydra\/core#",
      "openapi":"OpenApi\/openapi",
      "info":"OpenApi\/info",
      "servers":"OpenApi\/servers",
      "paths":"OpenApi\/paths",
      "components":"OpenApi\/components",
      "security":"OpenApi\/security",
      "tags":"OpenApi\/tags",
      "externalDocs":"OpenApi\/externalDocs",
      "extensionProperties":"OpenApi\/extensionProperties"
   },
   "@type":"OpenApi",
   "@id":"_:17018",
   "openapi":"3.0.3",
```

**Possible Solution**  

I imagine it has to do with the OpenAPI changes in master recently

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3844 
| License       | MIT
| Doc PR        | na

### CODE REVIEW

File: src/Documentation/Action/DocumentationAction.php [hunk 1]
```diff
@@ -85,7 +85,7 @@ public function __invoke(Request $request = null): DocumentationInterface
             $this->formats = $this->formatsProvider->getFormatsFromAttributes($attributes ?? []);
         }
 
-        if (null !== $this->openApiFactory && isset($context) && 3 === $context['spec_version']) {
+        if ('json' === $request->attributes->get('_format') && null !== $this->openApiFactory && isset($context) && 3 === $context['spec_version']) {
```
Comment (dunglas) [inline src/Documentation/Action/DocumentationAction.php:88]:
```suggestion
        if ('json' === $request->attributes->get('_format') && null !== $this->openApiFactory && 3 === ($context['spec_version'] ?? null)) {
```

**Review by dunglas — APPROVED** [review]

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thanks @soyuka
