### PR TITLE
fix(hydra): remove duplicate @context in docs.jsonld (fixes #7222)

### LINKED ISSUE #7222: Hydra documentation returning with double @context (docs.jsonld)
**API Platform version(s) affected**: 4.1.16

**Description**  
Just updated to v4.1.16, and docs.jsonld is now returning a result with two @context entries.

Image

**Possible Solution**  
ApiPlatform\JsonLd\HydraContext - has already @context key in array

Image

ApiPlatform\Hydra\Serializer\DocumentationNormalizer
- computeDoc: line 556 - Adds a new @context entry to the documentation.
- getContext: line 580 - Returns HYDRA_CONTEXT merged with another array that already contains @context

Image

An array merge would do the trick.
```
return array_merge(HYDRA_CONTEXT['@context'] ?? [],
[
    '@vocab' => $this->urlGenerator->generate('api_doc', ['_format' => self::FORMAT], UrlGeneratorInterface::ABS_URL) . '#',
    'hydra' => ContextBuilderInterface::HYDRA_NS,
    'rdf' => ContextBuilderInterface::RDF_NS,
    'rdfs' => ContextBuilderInterface::RDFS_NS,
    'xmls' => ContextBuilderInterface::XML_NS,
    'owl' => ContextBuilderInterface::OWL_NS,
    'schema' => ContextBuilderInterface::SCHEMA_ORG_NS,
    'domain' => ['@id' => 'rdfs:domain', '@type' => '@id'],
    'range' => ['@id' => 'rdfs:range', '@type' => '@id'],
    'subClassOf' => ['@id' => 'rdfs:subClassOf', '@type' => '@id'],
]);
```

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Related to https://github.com/api-platform/core/issues/7222
| License       | MIT

* Replace non-standard xmls: prefix with standard xsd: for XSD datatypes
* Remove redundant namespace declarations (hydra, rdf, rdfs, owl) from second context array
* Keep only application-specific overrides (schema, domain, range, subClassOf)

### CODE REVIEW

File: src/Hydra/Serializer/DocumentationNormalizer.php [hunk 1]
```diff
@@ -661,7 +661,7 @@ private function computeDoc(Documentation $object, array $classes, string $hydra
     private function getContext(string $hydraPrefix = ContextBuilder::HYDRA_PREFIX): array
     {
         return [
-            HYDRA_CONTEXT,
+            HYDRA_CONTEXT['@context'],
```
Comment (VincentLanglet) [inline src/Hydra/Serializer/DocumentationNormalizer.php]: You end up with two array in the context.

Is it ok or should it be an array_merge ?
