### PR TITLE
Fix the denormalization of \DateTime(Immutable) for ES documents

### LINKED ISSUE #3170: [BUG] DateTime denormalization fails with elasticsearch provider
Hi,

I've updated Api Platform to the 2.5 version and encountered one issue. I have an entity called User and it's populated into Elasticsearch index with FosElastica bundle. This entity has a DateTime field which is index like this: `2019-09-10T21:56:42+00:00`. Elastic support is turned on for this entity and when request is sent I get the following error:
```
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Cannot create an instance of DateTime from serialized data because its constructor requires parameter \"time\" to be present.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/var/www/html/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php",
      "line": 505,
      "args": []
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Normalizer",
      "short_class": "AbstractNormalizer",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractNormalizer",
      "type": "->",
      "function": "instantiateObject",
      "file": "/var/www/html/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php",
      "line": 231,
      "args": [
        [
          "array",
          [
            [
              "string",
              "2019-09-10T21:56:38+00:00"
            ]
          ]
        ],
        [
          "string",
          "DateTime"
        ],
        [
          "array",
          {
            "allow_extra_attributes": [
              "boolean",
              true
            ],
            "cache_key": [
              "string",
              "49699be3ed7cab8b271ee7c0939c6d8e"
            ]
          }
        ],
        [
          "object",
          "ReflectionClass"
        ],
        [
          "boolean",
          false
        ],
        [
          "string",
          "elasticsearch"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Normalizer",
      "short_class": "AbstractObjectNormalizer",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
      "type": "->",
      "function": "instantiateObject",
      "file": "/var/www/html/vendor/symfony/serializer/Normalizer/AbstractObjectNormalizer.php",
      "line": 330,
      "args": [
        [
          "array",
          [
            [
              "string",
              "2019-09-10T21:56:38+00:00"
            ]
          ]
        ],
        [
          "string",
          "DateTime"
        ],
        [
          "array",
          {
            "allow_extra_attributes": [
              "boolean",
              true
            ],
            "cache_key": [
              "string",
              "49699be3ed7cab8b271ee7c0939c6d8e"
            ]
          }
        ],
        [
          "object",
          "ReflectionClass"
        ],
        [
          "boolean",
          false
        ],
        [
          "string",
          "elasticsearch"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\Serializer\\Normalizer",
      "short_class": "AbstractObjectNormalizer",
      "class": "Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer",
      "type": "->",
      "function": "denormalize",
      "file": "/var/www/html/vendor/api-platform/core/src/Bridge/Elasticsearch/Serializer/ItemNormalizer.php",
      "line": 62,
      "args": [
        [
          "string",
          "2019-09-10T21:56:38+00:00"
        ],
        [
          "string",
          "DateTime"
        ],
        [
          "string",
          "elasticsearch"
        ],
        [
          "array",
          {
            "allow_extra_attributes": [
              "boolean",
              true
            ],
            "cache_key": [
              "string",
              "49699be3ed7cab8b271ee7c0939c6d8e"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\Bridge\\Elasticsearch\\Serializer",
      "short_class": "ItemNormalizer",
      "class": "ApiPlatform\\Core\\Bridge\\Elasticsearch\\Serializer\\ItemNormalizer",
      "type": "->",
      "function": "denormalize",
      "file": "/var/www/html/vendor/symfony/serializer/Serializer.php",
      "line": 191,
      "args": [
        [
          "string",
          "2019-09-10T21:56:38+00:00"
        ],
        [
          "string",
          "DateTime"
        ],
        [
          "string",
          "elasticsearch"
        ],
        [
          "array",
          {
            "allow_extra_attributes": [
              "boolean",
              true
            ],
            "cache_key": [
              "string",
              "49699be3ed7cab8b271ee7c0939c6d8e"
            ]
          }
        ]
      ]
    }
...
```

I figured it has something to do with this pull request https://github.com/api-platform/core/pull/2921. It changed the priority for `api_platform.elasticsearch.normalizer.item` service to -890 which is higher then Symfony's `serializer.normalizer.datetime` (-910). So elasticsearch item normalizer tries to denormalize date time object now and fails.

I don't think `api_platform.elasticsearch.normalizer.item` should support DateTime serialization at all.

For now as a workaround I just lowered the priority for  date time normalizer in my `services.yml` to fix the issue:
```
serializer.normalizer.datetime:
    class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
    tags:
        - { name: serializer.normalizer,  priority: -889 }
```

### LINKED ISSUE #3908: [ES] Normalization \DateTimeImmutable throws MissingConstructorArgumentsException
**API Platform version(s) affected**: 2.5.8

**Description**  
When using Elasticsearch, normalizing `\DateTimeImmutable` fields throws a MissingConstructorArgumentsException

**How to reproduce**  
I have an entity with a `\DateTimeImmutable` field.

```php
class MyEntity
{
    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $date = null;

    public function getDate(): ?\DateTimeImmutable
    {
        return $this->date;
    }

    public function setDate(?\DateTimeImmutable $date): self
    {
        $this->date = $date;

        return $this;
    }
}
```
 I have an ES index setup for this entity, where I mapped this field to the [date](https://www.elastic.co/guide/en/elasticsearch/reference/current/date.html) type.
```yaml
fos_elastica:
  indexes:
    my_entity:  
      use_alias: true
      index_name: my_entity
      dynamic: strict
      properties:
        date:
          type: date
```
Populating via the [FOSElasticaBundle](https://github.com/FriendsOfSymfony/FOSElasticaBundle) works ok. When I fetch the data with a `GET` request, the following error is thrown:
```
Uncaught PHP Exception Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException: "Cannot create an instance of "DateTimeImmutable" from serialized data because its constructor requires parameter "time" to be present." at /srv/api/vendor/symfony/serializer/Normalizer/AbstractNormalizer.php line 394
```

**Additional Context**  
When I provide a `datetime_format` in the `$defaultContext` for the DateTimeNormalizer`, the normalization error disappears:
```yaml
Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
  arguments:
    $defaultContext:
      datetime_format: 'Y-m-d H:i:s'
```

This however lead to a new error in my PHPUnit tests:
```
App\Tests\Functional\Entity\MyEntity::testPostItemRequest
Failed asserting that Array &0 (
    '@context' => '/api/contexts/MyEntity'
    '@id' => '/api/my_entity/0f0e11b6-dccd-4f3e-8318-0be53e87a5d6'
    '@type' => 'MyEntity'
    'date' => '2020-12-16 17:15:17'
) matches the provided JSON Schema.
date: Invalid date-time "2020-12-16 17:15:17", expected format YYYY-MM-DDThh:mm:ssZ or YYYY-MM-DDThh:mm:ss+hh:mm
```
Thrown by this line:
```php
self::assertMatchesResourceItemJsonSchema(MyEntity::class);
```

Specifying the `datetime_format` in the `ApiResource` annotation has zero effect.  Both the `GET` request as the PHPUnit test fail with the same error messages:
```php
/**
 * @ApiResource(
 *     attributes={
 *         "normalization_context"={
 *             "datetime_format" = "Y-m-d H:i:s",
 *         },
 *     },
 * )
 **/
class MyEntity {}
```

What does work for both the `GET` request as the PHPUnit test is specifying the format in the `DateTimeNormalizer` service as [RFC3339](https://www.php.net/manual/en/class.datetimeinterface.php#datetime.constants.rfc3339):
```yaml
  Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:
    arguments:
      $defaultContext:
        datetime_format: 'Y-m-d\TH:i:sP'
```

My preferable outcome would be to not having to touch anything at all; I'm perfectly fine with the default `YYYY-MM-DDThh:mm:ssZ` or `YYYY-MM-DDThh:mm:ss+hh:mm` format. I would expect defining a `datetime_format` in the `normalization_context` would have an impact.

Probably related to https://github.com/api-platform/core/issues/3878

### PR DESCRIPTION
**Pull request by meyerbaptiste**
| Q             | A
| ------------- | ---
| Bug fix?      | yes 
| New feature?  | no 
| BC breaks?    | yes
| Deprecations? | no
| Tickets       | fixes #3908  fixes #3170 
| License       | MIT
| Doc PR        | n/A

This PR:
* Reverts the priority of the Elasticsearch documents normalizer from `-890` to `-922`.
* Introduces an item normalizer decorator that prevents the default `ApiPlatform\Core\Serializer\ItemNormalizer` from taking over for the `elasticsearch` format because of priorities when the bridge is enabled.
* Renames the `ApiPlatform\Core\Bridge\Elasticsearch\Serializer\ItemNormalizer` class to `ApiPlatform\Core\Bridge\Elasticsearch\Serializer\DocumentNormalizer` so that the role of the denormalizer is more explicit: to transform Elasticsearch documents into PHP objects. **This is a BC break however the class is marked as experimental.** Because of this, it might be better to apply this fix to `3.0`.

### CODE REVIEW

**Comment by soyuka** [comment]
@dunglas can we consider this as a bug fix?

**Comment by dunglas** [comment]
I don't think so. We must stop introducing such heavy changes in patch release imho.

File: tests/Fixtures/Elasticsearch/Model/Tweet.php [hunk 1]
```diff
@@ -73,12 +73,12 @@ public function setAuthor(User $author): void
         $this->author = $author;
     }
 
-    public function getDate(): ?\DateTimeInterface
```
Comment (soyuka) [inline tests/Fixtures/Elasticsearch/Model/Tweet.php:76]: DateTimeInterface still works?

Comment (meyerbaptiste) [reply tests/Fixtures/Elasticsearch/Model/Tweet.php:76]: Yes but you are right, I should add another test for `DateTimeInterface`.

**Comment by soyuka** [comment]
thanks @meyerbaptiste
