### PR TITLE
fix(graphql): nested collection for mongo

### LINKED ISSUE #6107: GraphQL MongoDB: Nested Collections
https://github.com/api-platform/core/pull/6038 was introduced (@jotwea) but we had mongodb tests disabled. I've skipped the test for now but it'd be nice to check what's going on: 

https://github.com/api-platform/core/blob/main/features/graphql/query.feature#L71 

Note that to run mongodb tests use the docker command + instructions from https://github.com/api-platform/core/blob/main/CONTRIBUTING.md#behat

### PR DESCRIPTION
**Pull request by jotwea**
| Q             | A
| ------------- | ---
| Branch?       | main
| Tickets       | Closes #6107 
| License       | MIT
| Doc PR        | api-platform/docs#... 

https://github.com/api-platform/core/pull/6038 was introduced but we had mongodb tests disabled. Though the new scenario has been disabled temporarily for mongo. I activated it again and updated the mongo test fixtures to represent the same case as the ORM ones do.

### CODE REVIEW

File: src/GraphQl/Resolver/Factory/ResolverFactory.php [hunk 1]
```diff
@@ -35,7 +35,7 @@ public function __invoke(?string $resourceClass = null, ?string $rootClass = nul
             // Data already fetched and normalized (field or nested resource)
             if ($body = $source[$info->fieldName] ?? null) {
                 // special treatment for nested resources without a resolver/provider
-                if ($operation instanceof Query && $operation->getNested() && !$operation->getResolver() && !$operation->getProvider()) {
+                if ($operation instanceof Query && $operation->getNested() && !$operation->getResolver() && (!$operation->getProvider() || $operation->getProvider() === $resourceClass)) {
```
Comment (soyuka) [inline src/GraphQl/Resolver/Factory/ResolverFactory.php:38]: mhh how is this possible? A provider shouldn't be a resource no?

File: tests/Fixtures/TestBundle/Document/MultiRelationsNestedPaginated.php [hunk 2]
```diff
@@ -17,7 +17,7 @@
 use ApiPlatform\Metadata\GraphQl\QueryCollection;
 use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
 
-#[ApiResource(graphQlOperations: [new QueryCollection(nested: true)])]
+#[ApiResource(graphQlOperations: [new QueryCollection(provider: self::class, nested: true)])]
```
Comment (soyuka) [inline tests/Fixtures/TestBundle/Document/MultiRelationsNestedPaginated.php:20]: you want to force the provider to `null`?

Comment (jotwea) [reply tests/Fixtures/TestBundle/Document/MultiRelationsNestedPaginated.php:20]: Exactly. I found no way how to do that. Setting the provider explicitely to `null` also resulted that the operation had the default provider. So my "trick" was to use the entity itself as a provider. I am open to other ideas or contribution.

Comment (jotwea) [reply tests/Fixtures/TestBundle/Document/MultiRelationsNestedPaginated.php:20]: Like the idea, will change it soon

Comment (jotwea) [reply tests/Fixtures/TestBundle/Document/MultiRelationsNestedPaginated.php]: Changed it and work like a charm.Thx

File: src/GraphQl/Resolver/Factory/ResolverFactory.php (hunk 1 above)
Comment (jotwea) [reply src/GraphQl/Resolver/Factory/ResolverFactory.php]: Changed it (see comment below)

**Comment by jotwea** [comment]
@soyuka I am done now with the changes you requested. The failing unit tests are not due to my changes (some deprecation notice). From my perspective this PR could be merged.

File: features/graphql/query.feature [hunk 3]
```diff
@@ -68,7 +68,6 @@ Feature: GraphQL query support
     And the JSON node "data.multiRelationsDummy.oneToManyRelations.edges[0].node.name" should match "#RelatedOneToManyDummy(1|3)2#"
     And the JSON node "data.multiRelationsDummy.oneToManyRelations.edges[2].node.name" should match "#RelatedOneToManyDummy(1|3)2#"
 
-  @createSchema @!mongodb
```
Comment (soyuka) [inline features/graphql/query.feature:71]: why this change? maybe that you want to remove mongodb only?

File: docs/public/index.php [hunk 4]
```diff
@@ -19,7 +19,7 @@
 use ApiPlatform\Playground\Kernel;
 
 if (!($guide = $_SERVER['APP_GUIDE'] ?? $_ENV['APP_GUIDE'] ?? null)) {
-    throw new \RuntimeException('No guide.');
+    throw new RuntimeException('No guide.');
```
Comment (soyuka) [inline docs/public/index.php:22]: can you revert this?

File: tests/Fixtures/TestBundle/Document/MultiRelationsDummy.php [hunk 5]
```diff
@@ -89,7 +89,7 @@ public function addOneToManyRelation(MultiRelationsRelatedDummy $relatedMultiUse
 
     public function getNestedCollection(): Collection
     {
-        return $this->nestedCollection;
+        return $this->nestedCollection->map(fn ($entry) => ['name' => $entry->name]);
```
Comment (soyuka) [inline tests/Fixtures/TestBundle/Document/MultiRelationsDummy.php:92]: I'm not fond of this why is this necessary?

Comment (jotwea) [reply tests/Fixtures/TestBundle/Document/MultiRelationsDummy.php:92]: this mapping function was neccessary because mongo ODM behaves different like ORM does. The ORM Entity provides a Collection with each entry being an associative array. The ODM Document on the other hand provides a Collection with each entry being an instance of `MultiRelationsNested` / `MultiRelationsNestedPaginated`. So my intention here was to align the Testables here to get the same results.

Without this mapper the case for `MultiRelationsNestedPaginated` gets broken in test. If this is not acceptable for you, you may undo this mapping and find another way - I was not able to.

**Comment by soyuka** [comment]
If you can add a documentation for that feature it'd be awesome, thanks!
