### PR TITLE
 fix #2094 by improving error message

### LINKED ISSUE #2094: Undefined index: subresource_context
I POST to a sub entity, document -> articles then i get the fallowing error:

File: vendor/api-platform/core/src/DataProvider/OperationDataProviderTrait.php
Line: 104
Undefined index: subresource_context

```
$attributes =
resource_class = "Entity\DocumentArticle"
collection_operation_name = "get"
receive = true
```

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets |  #2094
| License       | MIT
| Doc PR        |

### CODE REVIEW

File: src/DataProvider/OperationDataProviderTrait.php [hunk 1]
```diff
@@ -99,6 +99,10 @@ private function extractIdentifiers(array $parameters, array $attributes)
             return $id;
         }
 
+        if (!isset($attributes['subresource_context'])) {
+            throw new RuntimeException("We could not recognize which operation you're using, either you don't want the data to be read (use _api_receive=false) or make sure you declared the operation name (\"item_operation_name\", \"collection_operation_name\").");
```
Comment (teohhanhui) [inline src/DataProvider/OperationDataProviderTrait.php]: Either "item_operation_name" or "collection_operation_name" must be defined, unless "_api_receive" is set to false.

**Comment by teohhanhui** [comment]
Thanks @soyuka! :tada:
