### PR TITLE
fix(symfony): update for PHPUnit 10

### LINKED ISSUE #5426: Command "api:upgrade-resource" fails with sebastian/diff 5.x
**API Platform version(s) affected**: v2.7.10
<!-- Warning: if your version is 2.7 we ask you to try the 3.0 version. If the bug is present there we will fix it. If the bug is due to old 2.6 behavior we can't fix it.
In that last case we recommend to either upgrade to 3.0 or to temporarily replace concerned service with your own. -->

**Description**  
<!-- A clear and concise description of the problem. -->
Trying to run the `api:upgrade-resource` command in preparation for v3.x fails:

```
$ console api:upgrade-resource 
[2023-03-01T13:01:39.282475+01:00] console.CRITICAL: Error thrown while running command "api:upgrade-resource". Message: "Too few arguments to function SebastianBergmann\Diff\Differ::__construct(), 0 passed in /.../vendor/api-platform/core/src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php on line 218 and exactly 1 expected" {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function SebastianBergmann\\Diff\\Differ::__construct(), 0 passed in /.../vendor/api-platform/core/src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php on line 218 and exactly 1 expected at /.../vendor/sebastian/diff/src/Differ.php:44)","command":"api:upgrade-resource","message":"Too few arguments to function SebastianBergmann\\Diff\\Differ::__construct(), 0 passed in /.../vendor/api-platform/core/src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php on line 218 and exactly 1 expected"} []
[2023-03-01T13:01:39.283043+01:00] php.CRITICAL: Uncaught Error: Too few arguments to function SebastianBergmann\Diff\Differ::__construct(), 0 passed in /.../vendor/api-platform/core/src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php on line 218 and exactly 1 expected {"exception":"[object] (ArgumentCountError(code: 0): Too few arguments to function SebastianBergmann\\Diff\\Differ::__construct(), 0 passed in /.../vendor/api-platform/core/src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php on line 218 and exactly 1 expected at /.../vendor/sebastian/diff/src/Differ.php:44)"} []

In Differ.php line 44:
                                                                                                                                                                                                                                   
  Too few arguments to function SebastianBergmann\Diff\Differ::__construct(), 0 passed in /.../vendor/api-platform/core/src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php on line 218 and exactly 1 e  
  xpected                                                                                                                                                                                                                          
                                                                                                                                                                                                                                   

api:upgrade-resource [-d|--dry-run [DRY-RUN]] [-s|--silent] [-f|--force]
```

This is due to a constructor change of `Differ` with `sebastian/diff` 5.x:

https://github.com/sebastianbergmann/diff/commit/6fb7a31dc5eb83a7d67f9119aafc36e248d357e2

**How to reproduce**  
1. Install `api-platform/core` 2.7 and `phpunit/phpunit` 10.x which requires `sebastian/diff` 5.x
2. Run the `api:upgrade-resource` console command

### PR DESCRIPTION
**Pull request by mbrodala**
The Differ now expects a output builder as mandatory argument.

Fixes #5426

| Q             | A
| ------------- | ---
| Branch?       | 2.7 
| Tickets       | #5426 
| License       | MIT
| Doc PR        | n/a 

Update the `UpgradeApiResourceCommand` for changes in PHPUnit 10.

### CODE REVIEW

File: src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php [hunk 1]
```diff
@@ -215,7 +216,7 @@ private function getSubresources(): array
     private function printDiff(string $oldCode, string $newCode, OutputInterface $output): void
     {
         $consoleFormatter = new ColorConsoleDiffFormatter();
-        $differ = new Differ();
+        $differ = new Differ(new UnifiedDiffOutputBuilder());
```
Comment (soyuka) [inline src/Core/Bridge/Symfony/Bundle/Command/UpgradeApiResourceCommand.php:219]:
```suggestion
        $differ = class_exists(UnifiedDiffOutputBuilder::class) ? new Differ(new UnifiedDiffOutputBuilder()) :  new Differ();
```

**Comment by soyuka** [comment]
thanks!
