### PR TITLE
fix(laravel): jsonapi query parameters (page, sort, fields and include)

### LINKED ISSUE #6841: Support of JSON:API defined query parameter usage
**Description**  
API Platform supports JSON:API format but only for request/response body. However the JSON:API specification is not limited to this. It specifies the usage of query parameters for [sorting](https://jsonapi.org/format/#fetching-sorting), [pagination and filtering](https://jsonapi.org/format/#query-parameters-families) too.

**Example** 

Sorting:

```
GET /people?sort=age HTTP/1.1
Accept: application/vnd.api+json
```

```
GET /people?sort=age,name HTTP/1.1
Accept: application/vnd.api+json
```

```
GET /articles?sort=-created,title HTTP/1.1
Accept: application/vnd.api+json
```

Pagination:

```
GET /?page[offset]=0&page[limit]=10
```

Filtering: 

```
GET /posts?sort=author.name&filter[author.status]=active
```

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 4.0 (this feature should be supported by Laravel)
| Tickets       | Closes #6841
| License       | MIT

### CODE REVIEW

File: src/JsonApi/Filter/SparseFieldset.php [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+            'type' => 'array',
+            'items' => [
+                'type' => 'string',
+            ],
+        ];
+    }
+
+    public function getOpenApiParameters(MetadataParameter $parameter): Parameter|array|null
+    {
+        $example = \sprintf(
```
Comment (dunglas) [inline src/JsonApi/Filter/SparseFieldset.php:38]: This variable seems useless, you could likely have a single `sprintf`

**Review by dunglas — APPROVED** [review]
LGTM
