### PR TITLE
fix(doctrine): group or filter in an AndWhere

### LINKED ISSUE #7441: OrFilter produces incorrect Doctrine query while using with extension
**API Platform version(s) affected**: 4.2.*

**Description**  
I'm playing with the new filter system in ApiPlatform 4.2, especially the OrFilter. It looks amazing!

However, I'm running into an issue with the Doctrine query when I also use the extension. I want to search in name, email, and phone properties. Here is my filter declaration:

```php
new GetCollection(
	parameters: [
		'search' => new QueryParameter(
			filter: new FreeTextQueryFilter(
				new OrFilter(new PartialSearchFilter()),
				properties: ['name', 'email', 'phone']
			),
		),
	]
),
```

I also use the extension, which filters all queries by the organization. When I try to search records (search: Test), the query looks like 

```sql
WHERE c0_.organization_id = ? OR LOWER(c0_.name) LIKE ? OR LOWER(c0_.email) LIKE ? OR LOWER(c0_.phone) LIKE ?
```

That gives incorrect results. Basically, the result is the same, as I wouldn't use the search filter at all. Is there a way to get a query like

```sql
WHERE c0_.organization_id = ? AND (LOWER(c0_.name) LIKE ? OR LOWER(c0_.email) LIKE ? OR LOWER(c0_.phone) LIKE ?)
```

so that the OrFilter can work with other filters/extensions?

**How to reproduce**  
Create an extension that filters all queries by some field and define query parameter as stated above. Then call the endpoint with search query string.

**Possible Solution**  

**Additional Context**  
Originally asked in discussion https://github.com/api-platform/core/discussions/7429

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Closes  #7441
| License       | MIT

TODO: do the same on the ODM filter ?

### CODE REVIEW

File: src/Doctrine/Orm/Filter/FreeTextQueryFilter.php [hunk 1]
```diff
@@ -46,14 +47,26 @@ public function apply(QueryBuilder $queryBuilder, QueryNameGeneratorInterface $q
...
         }
+
+        $queryBuilder->andWhere($qb->getDQLPart('where'));
+        $parameters = $queryBuilder->getParameters();
+
+        foreach ($qb->getParameters() as $p) {
+            $parameters->add($p);
+        }
+
+        $queryBuilder->setParameters($parameters);
```
Comment (fvozar) [inline src/Doctrine/Orm/Filter/FreeTextQueryFilter.php:70]: I think this will remove all previous parameters, for example, from an extension. A safer approach would be to use `$queryBuilder->getParameters()->add()` in a loop. At least that was what I did while playing with a workaround for this issue.

Comment (soyuka) [reply src/Doctrine/Orm/Filter/FreeTextQueryFilter.php:70]: its exactly what I do I collect the parameters and add them back above no?

Comment (fvozar) [reply src/Doctrine/Orm/Filter/FreeTextQueryFilter.php:70]: oh, yes, you are right. Row 64. Sorry for false alarm

**Comment by soyuka** [comment]
after analysis with mongodb odm it should work as each addition is a new match in our system (currently). I'm wondering if we couldn't build a single match to improve performances.
