### PR TITLE
fix(openapi): not forbidden response on openAPI doc

### LINKED ISSUE #6872: Not 403 response on openAPI
**API Platform version(s) affected**: 3.3.0

**Description**  
On an apiResource, we set a security but this not appear on the swagger

**How to reproduce**  
```php
#[ApiResource(
    operations: [
        new GetCollection()],
    security: "is_granted('ROLE_ADMIN')"
)]
class Author
{
}
```

then on the documentation, i like to see a 403 response like the one i get if I don't have access
like this : 
image

**Possible Solution**  

**Additional Context**

### PR DESCRIPTION
**Pull request by vinceAmstoutz**
| Q             | A
| ------------- | ---
| Branch?       | `3.4`
| Tickets       | Closes #6872 
| License       | MIT

Add OpenAPI documentation for the forbidden responses (see issue #6872 for more details).

### CODE REVIEW

**Comment by vinceAmstoutz** [comment]
@p-pichet This patch should resolve your issue, as shown below:
image

 @soyuka Could you help me with adding tests? I'm encountering some issues with the large  [OpenApiFactoryTest](https://github.com/vinceAmstoutz/api-platform-core/blob/fc8fa00a19320b65547a60537261959c11f8e6a8/src/OpenApi/Tests/Factory/OpenApiFactoryTest.php)

**Comment by vinceAmstoutz** [comment]
A proposal by message from @vincentchalamon to add `Forbidden` instead of `Forbidden: You must meet following condition(s) to access this resource: ....` mainly for security reasons. 

What is your opinion? @dunglas @soyuka 

Did it suit your needs? @p-pichet

**Comment by p-pichet** [comment]
> A proposal by message from @vincentchalamon to add `Forbidden` instead of `Forbidden: You must meet following condition(s) to access this resource: ....` mainly for security reasons.
> 
> What is your opinion? @dunglas @soyuka
> 
> Did it suit your needs? @p-pichet

In first thought, i think `forbidden` is enough and avoid to display to much but in second tought, i don't know. 

By the way, do it work with this case 
```
#[ApiResource(
operations : [], // all endpoints 
security: 'is_granted()' 
)]
class MyResource
```

**Comment by vinceAmstoutz** [comment]
> > A proposal by message from @vincentchalamon to add `Forbidden` instead of `Forbidden: You must meet following condition(s) to access this resource: ....` mainly for security reasons.
> > What is your opinion? @dunglas @soyuka
> > Did it suit your needs? @p-pichet
> 
> In first thought, i think `forbidden` is enough and avoid to display to much but in second tought, i don't know.
> 
> By the way, do it work with this case
> 
> ```
> #[ApiResource(
> operations : [], // all endpoints 
> security: 'is_granted()' 
> )]
> class MyResource
> ```

Thanks for your response!

Yes, it should work with your example. I'll add some tests with this scenario to make sure.

File: src/OpenApi/Factory/OpenApiFactory.php [hunk 1]
```diff
@@ -408,6 +408,13 @@ private function collectPaths(ApiResource $resource, ResourceMetadataCollection
                 }
             }
 
+            if (true === $overrideResponses && !isset($existingResponses[403]) && $security = $operation->getSecurity()) {
+                $openapiOperation = $openapiOperation->withResponse(403, new Response(\sprintf(
+                    'Forbidden: You must meet the following condition(s) to access this resource: %s.',
+                    $security
+                )));
```
Comment (soyuka) [inline src/OpenApi/Factory/OpenApiFactory.php:415]:
```suggestion
                $openapiOperation = $openapiOperation->withResponse(403, new Response('Forbidden'));
```

I don't think that we should disclose any user configuration inside the documentation, WDYT?

Comment (vinceAmstoutz) [reply src/OpenApi/Factory/OpenApiFactory.php]: @soyuka Solved. All that remains is to add tests.

**Review by p-pichet — APPROVED** [review]
Thanks a lot for the work

**Comment by vinceAmstoutz** [comment]
Tests DONE :ballot_box_with_check:  @soyuka

**Comment by soyuka** [comment]
Thanks!
