### PR TITLE
fix: ensure OpenAPI-specific implementation for nullable types does not influence the other ones

### LINKED ISSUE #4621: assertMatchesResourceItemJsonSchema returns invalid error "NULL value found, but an integer is required"
I just installed the latest version (2.6.7) of api-platform and I see new errors which did not arrive before.

In test I run this command:

`self::assertMatchesResourceItemJsonSchema(PayoutEntity::class);`

Then I receive:
```
App\Tests\EndpointTest::testGetPayoutItem
Failed asserting that Array &0 (
    'id' => '44a20ebe-9835-349b-9d16-3d3ec972d976'
    'netPay' => null
) matches the provided JSON Schema.
netPay: NULL value found, but an integer is required
```

Definition in PayoutEntity:

```class PayoutEntity
{
    /**
     * @ORM\Id
     * @ORM\Column(type="string")
     * @Groups({"payout"})
     *
     * @ApiProperty(openapiContext={"maxLength": 40})
     */
    private string $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     * @Groups({"payout"})
     *
     * @ApiProperty(openapiContext={"type":"integer", "nullable": true},
     *     description="Net pay in cents")
     */
    private ?int $netPay;
}
```

Validation doesn't use nullable parameter from @ApiProperty annotation

### PR DESCRIPTION
**Pull request by Deuchnord**
| Q             | A
| ------------- | ---
| Branch?       | main 
| Tickets       | fix #4621 
| License       | MIT

Fixing a bug that prevents the `ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestAssertionsTrait::assertMatchesResourceItemJsonSchema()` method from validating against JSON-Schema correctly for some nullable properties.

### CODE REVIEW

File: src/JsonSchema/TypeFactory.php [hunk 1]
```diff
@@ -169,10 +169,15 @@ private function addNullabilityToTypeDefinition(array $jsonSchema, Type $type, ?
         }
 
         if (\array_key_exists('$ref', $jsonSchema)) {
-            return [
-                'nullable' => true,
-                'anyOf' => [$jsonSchema],
-            ];
+            $typeDefinition = ['anyOf' => $jsonSchema];
+
+            if ($schema && Schema::VERSION_OPENAPI === $schema->getVersion()) {
```
Comment (alanpoulain) [inline src/JsonSchema/TypeFactory.php:174]: Please make sure you are in a JSON Schema context, not an OpenAPI one: nullable is not available for OpenAPI >= 3.1.

**Review by alanpoulain — APPROVED** [review]
