### PR TITLE
fix #518 - Add an exception to show that the value is not readable. 

### LINKED ISSUE #518: Wrong error message on invalid value during denormalization of relation
Suppose we pass a non-string non-object to a not writable relation, the error message is:
> Nested objects for attribute "%s" of "%s" are not enabled. Use serialization groups to change that behavior.

Which is not helpful because it's misleading.

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #518
| License       | MIT
| Doc PR        | 0

According to the normalizer, we could not pass  a string to one relation.

@teohhanhui is it ok like this ? not sure about the message

### CODE REVIEW

File: src/JsonLd/Serializer/ItemNormalizer.php [hunk 1]
```diff
@@ -306,6 +306,12 @@ private function denormalizeRelation(string $resourceClass, string $attributeNam
             return $this->serializer->denormalize($value, $className, self::FORMAT, $this->createRelationContext($className, $context));
         }
 
+        if (!is_object($value) && !is_array($value)) {
```
Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: In what cases would it be an `object`?

File: src/JsonLd/Serializer/ItemNormalizer.php [hunk 2]
```diff
@@ -306,6 +306,12 @@ private function denormalizeRelation(string $resourceClass, string $attributeNam
...
+            throw new InvalidArgumentException(sprintf(
+                '%s is nor a Iri string neither an object. You have to pass either an Iri or an Object',
```
Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: Perhaps something along the lines of:

```php
sprintf('Expected IRI or nested object, %s given.', ...)
```

File: src/JsonLd/Serializer/ItemNormalizer.php [hunk 3]
```diff
@@ -306,6 +306,12 @@ private function denormalizeRelation(string $resourceClass, string $attributeNam
...
+                $attributeName
+            ));
+        }
```
Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: Please add a blank line after this for better readability.

File: src/JsonLd/Serializer/ItemNormalizer.php (hunk 1 above)
Comment (Simperfit) [inline src/JsonLd/Serializer/ItemNormalizer.php]: I don't think thats impossible, if you pass

Comment (Simperfit) [inline src/JsonLd/Serializer/ItemNormalizer.php]: You are right, nothing can be a object in here.

Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: Actually, I'm not sure anymore after symfony/symfony#17660

@dunglas Are we due for a rewrite?

File: src/JsonLd/Serializer/ItemNormalizer.php (hunk 3 above)
Comment (Simperfit) [inline src/JsonLd/Serializer/ItemNormalizer.php]: StyleCI don't want me to do it

Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: You misunderstood. I mean a blank line after this `if` block.

Comment (Simperfit) [inline src/JsonLd/Serializer/ItemNormalizer.php]: I've test all space, he don't me do it

File: src/JsonLd/Serializer/ItemNormalizer.php [hunk 4]
```diff
@@ -306,6 +306,12 @@ private function denormalizeRelation(string $resourceClass, string $attributeNam
             return $this->serializer->denormalize($value, $className, self::FORMAT, $this->createRelationContext($className, $context));
         }
 
+        if (!is_array($value)) {
+            throw new InvalidArgumentException(sprintf(
+                'Expected IRI or nested object, %s given.',
+                $attributeName
```
Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: Why do you put `$attributeName` here? It's supposed to be the type... :laugh:

File: src/JsonLd/Serializer/ItemNormalizer.php (hunk 3 above)
Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: That was a different issue. You had trailing whitespaces...

File: features/invalid_data.feature [hunk 5]
```diff
@@ -35,6 +35,23 @@ Feature: Handle properly invalid data submitted to the API
     }
     """
 
+  Scenario: Get an error during deserialization of collection
```
Comment (teohhanhui) [inline features/invalid_data.feature]:
```gherkin
Scenario: Create a resource with wrong value type for relation
```

File: src/JsonLd/Serializer/ItemNormalizer.php (hunk 4 above)
Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]:
```php
throw new InvalidArgumentException(sprintf(
    'Expected IRI (string) or nested resource (array), "%s" given.',
    is_object($value) ? get_class($value) : gettype($value)
));
```

Comment (Simperfit) [inline src/JsonLd/Serializer/ItemNormalizer.php]: To know what property is wrong ?

If we give them juste the type it may be complicated to know where it come from no ?

Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]: Uhh, I see... We should expand the error message then :smile:

Comment (teohhanhui) [inline src/JsonLd/Serializer/ItemNormalizer.php]:
```php
throw new InvalidArgumentException(sprintf(
    'Expected IRI or nested object for attribute "%s" of "%s", "%s" given.',
    $attributeName,
    $resourceClass,
    is_object($value) ? get_class($value) : gettype($value),
));
```

**Comment by dunglas** [comment]
👍

**Comment by dunglas** [comment]
Thank you @Simperfit
