### PR TITLE
Bug Fix: DataTransformer returning same class as original should include JSONLD Data

### LINKED ISSUE #3474: Using Data Transformer which returns same class == missing extended data in JSONLD
API Platform version(s) affected: 2.5.4

Description
I want to trigger some DataTransformers on resources but instead of using a different class, I simply want to add some data to some of the properties on the existing class's properties. So to trigger the DataTransformer I set the output class of the resource to it's own class name again. This then triggers the Data Transformers to be detected and executed.

The issue is that when this happens the additional data expected in JSONLD vs JSON is missing. The @id, @context etc. This happens whether there is a transformer that is supported or not.

How to reproduce
Set an output class on a API Platform resource and request it as jsonld

Possible Solution
Unfortunately I haven't been able to trace where this is happening yet but I will update tomorrow once I continue to investigate why this happens.

Additional Context
I think this is enough information but I'll be happy to elaborate on any points here or admit my mistakes if I am going about this the wrong way. Thank you in advance.

### PR DESCRIPTION
**Pull request by silverbackdan**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3474
| License       | MIT
| Doc PR        | api-platform/docs#...

In `ApiPlatform\Core\DataTransformer\DataTransformerInterface` there is a comment that states that DTOs should be allowed to return the same original object if no transformation is done. This resulted in missing LD data. (No @id, @context etc.).
```php
     /**
     * Transforms the given object to something else, usually another object.
     * This must return the original object if no transformation has been done.
     *
     * @param object $object
     *
     * @return object
     */
    public function transform($object, string $to, array $context = []);
```
This update checks if the output class is the same as the original, and if so populated the extended metadata in the JsonLd\ItemNormalizer as it would not be added using the JsonLd\ObjectNormalizer

### CODE REVIEW

**Comment by silverbackdan** [comment]
Scrutinizer does not appear to be related to this PR.

Behat test added.

If this shouldn't be allowed perhaps it's worth throwing some kind of exception, but it does seem a pretty useful way of using this feature for me and it doesn't seem to cost much to allow this feature to be used in this way.

**Comment by silverbackdan** [comment]
I've just noticed this won't fix if the DTO returns the original object but the output class was set to something else which is what the comment in the interface describes should be allowed. That's because the checks to see if the object is different happens in the parent class to the JsonLd normalizer... Not sure how to address that though. Comments welcome.

**Comment by silverbackdan** [comment]
The latest commit handles both scenarios by using a context key. As the original resource will use the item normalizer that supports API Platform resources, this context key allows us to prevent an infinite loop.

**Comment by silverbackdan** [comment]
All test failures appear to be related to the 2.5 branch and not this PR.

**Comment by soyuka** [comment]
@teohhanhui  do you have thoughts on this? I think it's good, just not fond of the context to prevent recursion.

File: src/Serializer/AbstractItemNormalizer.php [hunk 1]
```diff
@@ -637,9 +645,8 @@ protected function getDataTransformer($data, string $to, array $context = []): ?
      * For a given resource, it returns an output representation if any
      * If not, the resource is returned.
      */
-    protected function transformOutput($object, array $context = [])
+    protected function transformOutput($object, string $outputClass, array $context = [])
```
Comment (silverbackdan) [inline src/Serializer/AbstractItemNormalizer.php:648]: I'm thinking that to prevent BC change here perhaps it is better to add the parameter at the end with a default to null and to reinstate the call to `getOutputMethod` if it is null. I removed to prevent a duplicate call but failed to think about others who may be extending this class as it is not marked `@internal`

Comment (soyuka) [reply src/Serializer/AbstractItemNormalizer.php:648]: :+1: indeed

File: tests/Fixtures/TestBundle/DataTransformer/OutputDtoSameClassTransformer.php [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+
+use ApiPlatform\Core\DataTransformer\DataTransformerInterface;
+use ApiPlatform\Core\Tests\Fixtures\TestBundle\Document\DummyDtoOutputFallbackToSameClass as DummyDtoOutputFallbackToSameClassDocument;
+use ApiPlatform\Core\Tests\Fixtures\TestBundle\Document\DummyDtoOutputSameClass as DummyDtoOutputSameClassDocument;
+use ApiPlatform\Core\Tests\Fixtures\TestBundle\Dto\OutputDtoDummy;
+use ApiPlatform\Core\Tests\Fixtures\TestBundle\Entity\DummyDtoOutputFallbackToSameClass;
+use ApiPlatform\Core\Tests\Fixtures\TestBundle\Entity\DummyDtoOutputSameClass;
+
+/**
+ * OutputDtoUnmodifiedDataTransformer.
```
[the remark this answers is not in the document]
Comment (silverbackdan) [reply tests/Fixtures/TestBundle/DataTransformer/OutputDtoSameClassTransformer.php]: Thank you, I've applied these changes and rebased.

File: src/Serializer/AbstractItemNormalizer.php (hunk 1 above)
Comment (silverbackdan) [reply src/Serializer/AbstractItemNormalizer.php]: Thanks!

**Comment by silverbackdan** [comment]
Hi, I did make these changes but I think I did something wrong with rebasing and I'm not sure how to notify that the changes requested are done ... so this is me doing that.

File: src/Serializer/AbstractItemNormalizer.php [hunk 3]
```diff
@@ -51,6 +51,8 @@ abstract class AbstractItemNormalizer extends AbstractObjectNormalizer
     use ContextTrait;
     use InputOutputMetadataTrait;
 
+    public const IS_TRANSFORMED_TO_SAME_CLASS_CONTEXT_KEY = 'is_transformed_to_same_class';
```
Comment (vincentchalamon) [inline src/Serializer/AbstractItemNormalizer.php:54]:
```suggestion
    public const IS_TRANSFORMED_TO_SAME_CLASS = 'is_transformed_to_same_class';
```

File: tests/Fixtures/TestBundle/Document/DummyDtoOutputFallbackToSameClass.php [hunk 4]
```diff
@@ -0,0 +1,55 @@
...
+namespace ApiPlatform\Core\Tests\Fixtures\TestBundle\Document;
+
+use ApiPlatform\Core\Annotation\ApiResource;
+use ApiPlatform\Core\Tests\Fixtures\TestBundle\Dto\OutputDtoDummy;
+use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
+
+/**
+ * Dummy InputOutput.
+ *
+ * @author Kévin Dunglas <dunglas@gmail.com>
```
Comment (vincentchalamon) [inline tests/Fixtures/TestBundle/Document/DummyDtoOutputFallbackToSameClass.php:23]:
```suggestion
 * @author Daniel West <daniel@silverback.is>
```

File: tests/Fixtures/TestBundle/Entity/DummyDtoOutputFallbackToSameClass.php [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+namespace ApiPlatform\Core\Tests\Fixtures\TestBundle\Entity;
+
+use ApiPlatform\Core\Annotation\ApiResource;
+use ApiPlatform\Core\Tests\Fixtures\TestBundle\Dto\OutputDtoDummy;
+use Doctrine\ORM\Mapping as ORM;
+
+/**
+ * Dummy InputOutput.
+ *
+ * @author Kévin Dunglas <dunglas@gmail.com>
```
Comment (vincentchalamon) [inline tests/Fixtures/TestBundle/Entity/DummyDtoOutputFallbackToSameClass.php:23]:
```suggestion
 * @author Daniel West <daniel@silverback.is>
```

File: tests/Fixtures/TestBundle/Document/DummyDtoOutputSameClass.php [hunk 6]
```diff
@@ -0,0 +1,54 @@
...
+
+namespace ApiPlatform\Core\Tests\Fixtures\TestBundle\Document;
+
+use ApiPlatform\Core\Annotation\ApiResource;
+use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
+
+/**
+ * Dummy InputOutput.
+ *
+ * @author Kévin Dunglas <dunglas@gmail.com>
```
Comment (vincentchalamon) [inline tests/Fixtures/TestBundle/Document/DummyDtoOutputSameClass.php:22]:
```suggestion
 * @author Daniel West <daniel@silverback.is>
```

File: tests/Fixtures/TestBundle/Entity/DummyDtoOutputSameClass.php [hunk 7]
```diff
@@ -0,0 +1,56 @@
...
+
+namespace ApiPlatform\Core\Tests\Fixtures\TestBundle\Entity;
+
+use ApiPlatform\Core\Annotation\ApiResource;
+use Doctrine\ORM\Mapping as ORM;
+
+/**
+ * Dummy InputOutput.
+ *
+ * @author Kévin Dunglas <dunglas@gmail.com>
```
Comment (vincentchalamon) [inline tests/Fixtures/TestBundle/Entity/DummyDtoOutputSameClass.php:22]:
```suggestion
 * @author Daniel West <daniel@silverback.is>
```

File: src/Serializer/AbstractItemNormalizer.php (hunk 3 above)
Comment (silverbackdan) [reply src/Serializer/AbstractItemNormalizer.php]: Applied changes

File: tests/Fixtures/TestBundle/Document/DummyDtoOutputFallbackToSameClass.php (hunk 4 above)
Comment (silverbackdan) [reply tests/Fixtures/TestBundle/Document/DummyDtoOutputFallbackToSameClass.php]: Applied changes

File: tests/Fixtures/TestBundle/Entity/DummyDtoOutputFallbackToSameClass.php (hunk 5 above)
Comment (silverbackdan) [reply tests/Fixtures/TestBundle/Entity/DummyDtoOutputFallbackToSameClass.php]: Applied changes

File: tests/Fixtures/TestBundle/Document/DummyDtoOutputSameClass.php (hunk 6 above)
Comment (silverbackdan) [reply tests/Fixtures/TestBundle/Document/DummyDtoOutputSameClass.php]: Applied changes

File: tests/Fixtures/TestBundle/Entity/DummyDtoOutputSameClass.php (hunk 7 above)
Comment (silverbackdan) [reply tests/Fixtures/TestBundle/Entity/DummyDtoOutputSameClass.php]: Applied changes

**Comment by silverbackdan** [comment]
Thank you @vincentchalamon for the review - all changes applied now. I'll wait for core team's opinion.

**Comment by soyuka** [comment]
I like this, thanks @vincentchalamon @silverbackdan

**Comment by vincentchalamon** [comment]
@silverbackdan Could you please update your branch from the 2.5 remote branch?

**Comment by silverbackdan** [comment]
Thanks all! @vincentchalamon - I've just pressed the button to update from 2.5 remote - seems to have been able to merge without conflict.

**Comment by soyuka** [comment]
thanks @silverbackdan
