### PR TITLE
fix(jsonschema) don't skip remaining multiple union types

### LINKED ISSUE #6212: Properties with multiple type unions generate incorrect OpenAPI schema
**API Platform version(s) affected**: 3.2

**Description**  
Currently (3.2.16) with the model below the `owner` property will generate the schema:

```
"owner": {
    "anyOf": [
        {
            "$ref": "#/components/schemas/Wren"
        },
        {
            "type": "null"
        }
    ]
}
```

Instead of:
```
"owner": {
    "anyOf": [
        {
            "$ref": "#/components/schemas/Wren"
        },
        {
            "$ref": "#/components/schemas/Robin"
        },
        {
            "type": "null"
        }
    ]
}
```

**How to reproduce**  
```php
#[ApiResource]
#[ORM\Entity]
class Nest
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: 'bird')]
    private ?Bird $owner;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOwner(): ?Bird
    {
        return $this->owner;
    }

    public function setOwner(Wren|Robin|null $owner): static
    {
        $this->owner = $owner;

        return $this;
    }
}
```

```php
interface Bird
{
    public function getName(): ?string;

    public function getAge(): ?int;
}
```

```php
final class Robin implements Bird
{
    public ?string $name = null;
    public ?int $age = null;

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }
}
```

```php
final class Wren implements Bird
{
    public ?string $name = null;
    public ?int $age = null;
    public ?int $weight = null;

    public function getName(): ?string
    {
        return $this->name;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }
}
```

**Possible Solution**  
I dug in a bit and it stems from handling in `SchemaFactory::buildPropertySchema`. Simply removing the final `break` [here](https://github.com/api-platform/core/blob/2819d56c80f39a53f2e3d5fd7119566ad96b4075/src/JsonSchema/SchemaFactory.php#L240) make this particular problem disappear but breaks tests. So I hacked up a more robust proof-of-concept fix/patch below that addresses this issue (and passes existing tests). 

```diff
diff --git a/src/JsonSchema/SchemaFactory.php b/src/JsonSchema/SchemaFactory.php
index a128a8968..9a21d47d3 100644
--- a/src/JsonSchema/SchemaFactory.php
+++ b/src/JsonSchema/SchemaFactory.php
@@ -196,10 +196,13 @@
         // property schema is created in SchemaPropertyMetadataFactory, but it cannot build resource reference ($ref)
         // complete property schema with resource reference ($ref) only if it's related to an object
         $version = $schema->getVersion();
-        $subSchema = new Schema($version);
-        $subSchema->setDefinitions($schema->getDefinitions()); // Populate definitions of the main schema
+        $refs = [];
+        $isNullable = null;
+
+        foreach ($types as $type) {
+            $subSchema = new Schema($version);
+            $subSchema->setDefinitions($schema->getDefinitions()); // Populate definitions of the main schema
 
-        foreach ($types as $type) {
             // TODO: in 3.3 add trigger_deprecation() as type factories are not used anymore, we moved this logic to SchemaPropertyMetadataFactory so that it gets cached
             if ($typeFromFactory = $this->typeFactory?->getType($type, 'jsonschema', $propertyMetadata->isReadableLink(), $serializerContext)) {
                 $propertySchema = $typeFromFactory;
@@ -230,14 +233,25 @@
                 break;
             }
 
-            if ($type->isNullable()) {
-                $propertySchema['anyOf'] = [['$ref' => $subSchema['$ref']], ['type' => 'null']];
-            } else {
-                $propertySchema['$ref'] = $subSchema['$ref'];
+            $isNullable = $isNullable ?? $type->isNullable();
+            $refs[$subSchema['$ref']] = '$ref';
+        }
+
+        if (\count($refs) > 1) {
+            $anyOf = [];
+            foreach (array_keys($refs) as $ref) {
+                $anyOf[] = ['$ref' => $ref];
+            }
+            $propertySchema['anyOf'] = $anyOf;
+
+            if ($isNullable) {
+                $propertySchema['anyOf'][] = ['type' => 'null'];
             }
 
             unset($propertySchema['type']);
-            break;
+        } elseif (\count($refs) === 1) {
+            $propertySchema['$ref'] = array_keys($refs)[0];
+            unset($propertySchema['type']);
         }
 
         $schema->getDefinitions()[$definitionName]['properties'][$normalizedPropertyName] = new \ArrayObject($propertySchema);

```

### PR DESCRIPTION
**Pull request by GwendolenLynch**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Tickets       | Closes #6212 
| License       | MIT

As requested by @soyuka  

For the tests I just imported what I had in a sandbox to create the issue. Happy to modify on request.

### CODE REVIEW

File: tests/Fixtures/TestBundle/Entity/Issue6212/Nest.php [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+    {
+        return $this->id;
+    }
+
+    public function getOwner(): ?Bird
+    {
+        return $this->owner;
+    }
+
+    public function setOwner(Wren|Robin|null $owner): static
```
Comment (vincentchalamon) [inline tests/Fixtures/TestBundle/Entity/Issue6212/Nest.php:44]:
```suggestion
    public function setOwner(?Bird $owner): static
```

File: tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php [hunk 2]
```diff
@@ -124,6 +124,22 @@ public function testArraySchemaWithReference(): void
...
+        $json = json_decode($result, associative: true);
+
+        $this->assertEquals($json['definitions']['Nest.jsonld']['properties']['owner']['anyOf'], [
+            ['$ref' => '#/definitions/Wren.jsonld'],
+            ['$ref' => '#/definitions/Robin.jsonld'],
+            ['type' => 'null'],
+        ]);
+
+        $this->assertArrayHasKey('Wren.jsonld', $json['definitions']);
+        $this->assertArrayHasKey('Robin.jsonld', $json['definitions']);
```
Comment (vincentchalamon) [inline tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php:140]: I think this can be simply moved to `testArraySchemaWithReference`, as `testArraySchemaWithMultipleUnionTypes` is doing approximately the same

**Review by vincentchalamon — CHANGES_REQUESTED** [review]
Minor fixes. Need to fix the CI, then LGTM

File: tests/Fixtures/TestBundle/Entity/Issue6212/Nest.php (hunk 1 above)
Comment (GwendolenLynch) [reply tests/Fixtures/TestBundle/Entity/Issue6212/Nest.php:44]: Agreed that in this tiny model that looks wrong, but it is just meant to illustrate the bug. In this case, the concrete classes implement the `Bird` interface, but the `Robin` classes have an extra property. Normally I'd use a second interface but didn't want to overload the example/test :innocent: 

As I understand the flow, the `PropertyAccessor` uses the types on the setter (as a first option), and the additional (non-`null`) properties are currently not properly handled in the schema factory. So it is only the setter in this case using that signature.

File: tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php (hunk 2 above)
Comment (GwendolenLynch) [reply tests/JsonSchema/Command/JsonSchemaGenerateCommandTest.php:140]: I'm very willing to make changes, but am a bit confused as `Issue5793` resources don't have multiple type unions … or am I missing the obvious here?

**Comment by GwendolenLynch** [comment]
@vincentchalamon I have fixed the tests that are relevant. The PHPUnit ones are currently an indirect deprecation notice from `doctrine/doctrine-bundle@2.12`, and the Mongo ones are: 
```
TypeError: Doctrine\ODM\MongoDB\Mapping\Driver\AttributeDriver::__construct(): Argument #2 ($reader) must be of 
type ?Doctrine\Common\Annotations\Reader, Doctrine\ODM\MongoDB\Mapping\Driver\AttributeReader given
```

Can I get away without fixing those? :wink:

**Comment by vincentchalamon** [comment]
> @vincentchalamon I have fixed the code that addresses tests that are relevant. The PHPUnit ones are currently an indirect deprecation notice from `doctrine/doctrine-bundle@2.12`, and the Mongo ones are:
> 
> ```
> TypeError: Doctrine\ODM\MongoDB\Mapping\Driver\AttributeDriver::__construct(): Argument #2 ($reader) must be of 
> type ?Doctrine\Common\Annotations\Reader, Doctrine\ODM\MongoDB\Mapping\Driver\AttributeReader given
> ```
> 
> Can I get away without fixing those? 😉

Yep don't worry it's already blocked on 3.2 branch too :wink:

File: src/JsonSchema/SchemaFactory.php [hunk 3]
```diff
@@ -230,14 +233,33 @@ private function buildPropertySchema(Schema $schema, string $definitionName, str
                 break;
             }
 
-            if ($type->isNullable()) {
-                $propertySchema['anyOf'] = [['$ref' => $subSchema['$ref']], ['type' => 'null']];
-            } else {
-                $propertySchema['$ref'] = $subSchema['$ref'];
+            $isNullable = $isNullable ?? $type->isNullable();
+            $refs[$subSchema['$ref']] = '$ref';
```
Comment (vincentchalamon) [inline src/JsonSchema/SchemaFactory.php:237]: Value is never used as you're always calling `array_keys($refs)`. I guess you did it to ensure unicity, so I suggest the following:
```suggestion
            $ref = $subSchema['$ref'];
            if (!\in_array($ref, $refs, true)) {
                $refs[] = $ref;
            }
```
Then you can just use `$refs` instead of `array_keys($refs)`

Comment (vincentchalamon) [reply src/JsonSchema/SchemaFactory.php:237]: You can also update `$isNullable` as following:
```php
if ($type->isNullable() && !\in_array(['type' => 'null'], $refs, true)) {
    $refs[] = ['type' => 'null'];
}
```

Comment (vincentchalamon) [reply src/JsonSchema/SchemaFactory.php:237]: With those updates, you won't need `$isNullable` anymore on line 247, and won't need `$anyOf` neither

Comment (GwendolenLynch) [reply src/JsonSchema/SchemaFactory.php]: Pushed the changes. Thank you so much for thinking this though with me, it is already a much better outcome!

File: src/JsonSchema/SchemaFactory.php [hunk 4]
```diff
@@ -230,14 +233,17 @@ private function buildPropertySchema(Schema $schema, string $definitionName, str
...
-            }
+            $refs[] = ['$ref' => $subSchema['$ref']];
+            $isNullable = $isNullable ?? $type->isNullable();
+        }
+
+        if ($isNullable && !\in_array(['type' => 'null'], $refs, true)) {
+            $refs[] = ['type' => 'null'];
+        }
 
+        if (\count($refs) > 0) {
```
Comment (vincentchalamon) [inline src/JsonSchema/SchemaFactory.php:244]: What if `\count($refs) === 1`?

Comment (vincentchalamon) [reply src/JsonSchema/SchemaFactory.php:244]: Same: what if `$refs` is empty?

Comment (GwendolenLynch) [reply src/JsonSchema/SchemaFactory.php]: That's mildly embarrassing, but fixed now. :blush:

File: src/JsonSchema/SchemaFactory.php [hunk 5]
```diff
@@ -230,14 +233,19 @@ private function buildPropertySchema(Schema $schema, string $definitionName, str
...
+            $isNullable = $isNullable ?? $type->isNullable();
+        }
+
+        if ($isNullable) {
+            $refs[] = ['type' => 'null'];
+        }
 
+        if (\count($refs) > 1) {
+            $propertySchema['anyOf'] = $refs;
             unset($propertySchema['type']);
```
Comment (vincentchalamon) [inline src/JsonSchema/SchemaFactory.php:246]: If `anyOf` or `$ref` is specified, `type` must be removed.

File: src/JsonSchema/SchemaFactory.php [hunk 6]
```diff
@@ -230,14 +233,19 @@ private function buildPropertySchema(Schema $schema, string $definitionName, str
...
-            break;
+        } elseif (1 === \count($refs)) {
+            $propertySchema = $refs[0];
```
Comment (vincentchalamon) [inline src/JsonSchema/SchemaFactory.php:248]: This erases other options in `$propertySchema`, I'm not sure it's safe. We should just add/override `$propertySchema['$ref']` option.

File: src/JsonSchema/SchemaFactory.php (hunk 5 above)
Comment (GwendolenLynch) [reply src/JsonSchema/SchemaFactory.php:246]: I'm confused again. :innocent: The `unset()` is removing `type` isn't it?

Comment (vincentchalamon) [reply src/JsonSchema/SchemaFactory.php:246]: Yep!

Comment (vincentchalamon) [reply src/JsonSchema/SchemaFactory.php:246]: But you can move this line before (or after) the if to prevent duplication with line 249

Comment (GwendolenLynch) [reply src/JsonSchema/SchemaFactory.php:246]: Got it! Just to check your meaning though, as we don't want to unset `type` if `\count($refs) > 0`, is this whasat you're thinking?

```php
        if (\count($refs) > 1) {
            $propertySchema['anyOf'] = $refs;
        } elseif (1 === \count($refs)) {
            $propertySchema['$ref'] = $refs[0]['$ref'];
        }
        if (\count($refs) > 0) {
            unset($propertySchema['type']);
        }
```

For extra context, a resource with a `?int $property;` will have an empty `$refs` array, but `$propertySchema['type']` will contain `['integer', 'null']`

Comment (vincentchalamon) [reply src/JsonSchema/SchemaFactory.php:246]: Ah nice catch! I didn't think about this specific use case.
In this case, indeed I would prefer to keep duplication to avoid useless code complexity!
You can keep your code as it is

**Review by vincentchalamon — APPROVED** [review]

File: src/JsonSchema/SchemaFactory.php [hunk 7]
```diff
@@ -230,14 +233,20 @@ private function buildPropertySchema(Schema $schema, string $definitionName, str
...
-            }
+            $refs[] = ['$ref' => $subSchema['$ref']];
+            $isNullable = $isNullable ?? $type->isNullable();
+        }
 
+        if ($isNullable) {
+            $refs[] = ['type' => 'null'];
+        }
+
+        if (\count($refs) > 1) {
```
Comment (soyuka) [inline src/JsonSchema/SchemaFactory.php:244]: can we keep the \count in a variable to avoid counting twice?z
```suggestion
        if (($c = \count($refs)) > 1) {
```

use `(1 === $c)` later on

Comment (GwendolenLynch) [reply src/JsonSchema/SchemaFactory.php]: Done!

**Comment by soyuka** [comment]
Thanks! ci failures not related
