### PR TITLE
fix(serializer): Use serializer when denormalizing relation inside Input

### LINKED ISSUE #7831: Custom Denormalizer are not used anymore when deserializing relation inside Input
**API Platform version(s) affected**: 4.2.17 or 4.2.18

Related to the fixes (cc @soyuka)
https://github.com/api-platform/core/pull/7779
https://github.com/api-platform/core/pull/7787

With something like
```
#[ApiResource]
class Locale { private string $id; }

class MyInput { private Locale $locale }
```

When calling the endpoint with the data `['locale' => 'en']` it's expected to not denormalize the Locale since it's not an IRI.
But I wrote my custom LocaleDenormalizer which basically does `$this->entityManager->getRepository(Locale::class)->find($data);` and it worked find before the upgrade.

Looking at how it worked, 
- The serializer used the ItemNormalizer
- The class is changed, and now it used the ObjectNormalizer from Symfony (cf analyze from https://github.com/api-platform/core/issues/7705#issuecomment-3927707118) for $locale field.

Now, it use the ItemNormalizer and keep using it for the locale field. But then since this field is a string, it tries to resolve the IRI without calling the denormalizer on it. And I get a `Invalid IRI` error.

I think rather than always using the iriConverter, the ItemNormalizer should call serializer::normalize on the string value:
- If a denormalizer has a higher priority it will be used
- If not, it will fallback on the ItemNormalizer again which already handle string value with the IriConverter the right way.

A fix like https://github.com/api-platform/core/pull/7830

### PR DESCRIPTION
**Pull request by VincentLanglet**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Closes #7831
| License       | MIT
| Doc PR        | api-platform/docs#...

### CODE REVIEW

File: src/Serializer/Tests/AbstractItemNormalizerTest.php [hunk 1]
```diff
@@ -1253,7 +1253,6 @@ public function testDeserializationPathForNotDenormalizableRelations(): void
         $propertyAccessorProphecy = $this->prophesize(PropertyAccessorInterface::class);
 
         $serializerProphecy = $this->prophesize(SerializerInterface::class);
-        $serializerProphecy->willImplement(DenormalizerInterface::class);
```
Comment (VincentLanglet) [inline src/Serializer/Tests/AbstractItemNormalizerTest.php:1256]: If the serializer is a denormalizer, it will call it instead of the iriConverter and the mock are not properly configured for this in this test.

**Comment by soyuka** [comment]
Thanks!
