### PR TITLE
[GraphQL] Fix filter arguments order

### LINKED ISSUE #2808: [GraphQL] OrderFilter does not consider the order of the properties to filter on
When a resource is defined with an `OrderFilter` on multiple properties, the GRAPHQL endpoint does not keep the sorting of the properties (to filter on).

In the following example
```
/**
 * @ApiResource()
 */
class Dummy
{
   /** @var string */
   private $firstname;

   /** @var string */
   private $laststname;

   // ...
}
```
and the api-p filter service defintion :
```
dummy.order_filter:
    parent: api_platform.doctrine.orm.order_filter
    arguments:
       properties: 
          firstname: ~
          lastname: ~
```
Calling the REST endpoint `/dummies?order[lastname]=ASC&order[firstname]=ASC` returns the  expected results ; the `OrderFilter` is called and the `$context[filters][order]` argument is populated with the properties to filter on in the expected order (1st the `lastname` and 2nde the `firstname`)
```
context => [ 
  filters => [
    order => [
      lastname => ASC,
      firstname => ASC
    ]
  ]
]
```
So the SQL query is build keeping the properties sorting : 
`SELECT * FROM dummies ORDER BY lastname ASC, firstname ASC`

The issue is on the GRAPHQL endpoint that keeps the default order (defined in the service definition). 
Calling the syntax `dummies(order: {"lastname": "ASC", "firstname": "ASC"}) { ... }`, the SQL query is build keeping the default order :
`SELECT * FROM dummies ORDER BY firstname ASC, lastname ASC`
In this case, the `OrderFilter` is called and the `$context[filters][order]` argument is : 
```
context => [ 
  filters => [
    order => [
      firstname => ASC
      lastname => ASC,
    ]
  ]
]
```

### PR DESCRIPTION
**Pull request by ArnoudThibaut**
The InputObjectType doesn't preserve the order of the arguments passed to it and it's the order declared in the service declaration that is used. This can lead to bug when the order of the arguments matter, like with the OrderFilter for example.

The solution is to change the type of the filter argument from InputObjectType to a list of InputObjectType because the order of a list is preserved.

The "old" syntax `order: {foo: asc, bar: desc}` is still "working" (but it's buggy) and the following syntax should be used instead `order: [{foo: 'asc'}, {bar: 'desc'}]`

In the first commit there is a falling behat test that use the current syntax to order a collection across 2 fields, and the order is first apply one the field `name` before the field `description`.

| Q             | A
| ------------- | ---
| Bug fix?      | yes 
| New feature?  | no 
| BC breaks?    | not sur,the build-in filters are still working but I don't know if it can break custom filters
| Deprecations? | not yet, but I think we should find a way to depreciate the "old" syntax on the build-in filter that are buggy because of the order problem
| Tickets       | fixes #2808
| License       | MIT
| Doc PR        | TODO, as the old syntax is still usabled maybe we should add doc on how to use the filters with graphql

Ps: the unit tests are failing but I want to be sure on how preserve the right order and if we should apply the changes for all filter or just for the build-in one because I'm not sure if it can broke something :/

### CODE REVIEW

File: src/GraphQl/Resolver/Stage/ReadStage.php [hunk 1]
```diff
@@ -172,4 +177,19 @@ private function getSubresource(string $rootClass, array $rootResolvedFields, st
             'collection' => true,
         ], $operationName);
     }
+
+    private function isNumericIndexArrayOfArray(array $array): bool
```
Comment (alanpoulain) [inline src/GraphQl/Resolver/Stage/ReadStage.php]: I think it should be elsewhere, like in `Util/ArrayTrait` for instance.
Also, it should probably be split into two methods like `isSequentialArray` and `containsOnly` (maybe a more general method by using `gettype`).

File: features/graphql/filters.feature [hunk 2]
```diff
@@ -222,6 +222,31 @@ Feature: Collections filtering
...
+    }
+    """
+    Then the response status code should be 200
+    And the header "Content-Type" should be equal to "application/json"
+    And the JSON node "data.dummies.edges[0].node.name" should be equal to "baz"
+    And the JSON node "data.dummies.edges[0].node.description" should be equal to "bar"
+    And the JSON node "data.dummies.edges[1].node.name" should be equal to "foo"
+    And the JSON node "data.dummies.edges[1].node.description" should be equal to "bar"
+
+
```
Comment (alanpoulain) [inline features/graphql/filters.feature]: One line to remove (sorry :stuck_out_tongue:).

File: src/GraphQl/Resolver/Stage/ReadStage.php [hunk 3]
```diff
@@ -140,9 +140,14 @@ private function getNormalizedFilters(array $args): array
 
         foreach ($filters as $name => $value) {
             if (\is_array($value)) {
-                if (strpos($name, '_list')) {
+                if (\is_string($name) && strpos($name, '_list')) {
                     $name = substr($name, 0, \strlen($name) - \strlen('_list'));
                 }
+
+                // If it's just a simple array of string values, for example when using the _list syntax we don't want to decompose the array because it's will return multiple string and not multipe array that we can merge
```
Comment (alanpoulain) [inline src/GraphQl/Resolver/Stage/ReadStage.php]: I think you should invert the sense of this sentence to tell the developer when this `if` is applied.
Like:
If the value contains arrays, we need to merge them for the filters to understand this syntax, proper to GraphQL to preserve the order of the arguments.

**Comment by alanpoulain** [comment]
IMHO I think all the filters should have the same syntax if they are used in the same way (like the `exists` filter).

File: src/GraphQl/Resolver/Stage/ReadStage.php [hunk 4]
```diff
@@ -131,9 +133,14 @@ private function getNormalizedFilters(array $args): array
 
         foreach ($filters as $name => $value) {
             if (\is_array($value)) {
-                if (strpos($name, '_list')) {
+                if (\is_string($name) && strpos($name, '_list')) {
```
Comment (alanpoulain) [inline src/GraphQl/Resolver/Stage/ReadStage.php:136]: Why this check?

File: src/Util/ArrayTrait.php [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+
+trait ArrayTrait
+{
+    public function isNumericIndexArrayOfArray(array $array): bool
+    {
+        if (!$this->isSequentialArray($array)) {
+            return false;
+        }
+
+        return $this->arrayContainsOnly($array, \gettype([]));
```
Comment (alanpoulain) [inline src/Util/ArrayTrait.php:24]: Why not:
```suggestion
        return $this->arrayContainsOnly($array, 'array');
```

File: src/Util/ArrayTrait.php [hunk 6]
```diff
@@ -0,0 +1,42 @@
...
+        if ([] === $array) {
+            return false;
+        }
+
+        return array_keys($array) === range(0, \count($array) - 1);
+    }
+
+    public function arrayContainsOnly(array $array, string $type): bool
+    {
+        return $array === array_filter($array, static function ($item) use ($type) {
```
Comment (alanpoulain) [inline src/Util/ArrayTrait.php:38]:
```suggestion
        return $array === array_filter($array, static function ($item) use ($type): bool {
```

File: src/Util/ArrayTrait.php [hunk 7]
```diff
@@ -0,0 +1,42 @@
...
+ * file that was distributed with this source code.
+ */
+
+declare(strict_types=1);
+
+namespace ApiPlatform\Core\Util;
+
+trait ArrayTrait
+{
+    public function isNumericIndexArrayOfArray(array $array): bool
```
Comment (alanpoulain) [inline src/Util/ArrayTrait.php:18]: To be coherent:
```suggestion
    public function isSequentialArrayOfArrays(array $array): bool
```

**Comment by alanpoulain** [comment]
Thank you @ArnoudThibaut!
