### PR TITLE
fix(symfony): disable Swagger UI and keep openapi.json

### LINKED ISSUE #7544: Disable Swagger UI but keep openapi.json
**API Platform version(s) affected**: 4.2.6

**Description**  
We want to completely disable the bundled Swagger UI but keep the route for the json export.
Since we have several different apis to document we have a central Swagger UI container that loads the json from different apis.

**How to reproduce**  
enable_swagger: true
enable_swagger_ui: false
But this doesn't disable the bundled Swagger UI

**Possible Solution**  
?

**Additional Context**

### PR DESCRIPTION
**Pull request by Maxcastel**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Closes #7544 
| License       | MIT
| Doc PR        | na 

## Descripton

This PR fixes an issue where `enable_swagger_ui: false` did not actually disable the Swagger UI HTML interface.

Currently, when configuring `enable_swagger: true` and `enable_swagger_ui: false`, accessing the documentation route (`/api/docs`), still displays the Swagger UI HTML interface, ignoring the configuration (`enable_swagger_ui: false`) to disable it.

The goal is to fully disable the Swagger UI HTML interface while keeping the JSON documentation (`/api/docs.jsonopenapi`) accessible.

## Changes

- Modified `ApiPlatformExtension` to load Swagger UI services (definitions, listeners, providers) only if `enable_swagger_ui` is `true`.
- Updated `src/Symfony/Action/DocumentationAction.php` to throw a `NotFoundHttpException` when Swagger UI is disabled.

`src/Laravel/Controller/DocumentationController::getOpenApiDocumentation()` : 
```php
if ('html' === $format && $this->swaggerUiEnabled) {
    $operation = $operation->withProcessor('api_platform.swagger_ui.processor')->withWrite(true);
}
```

`src/Symfony/Action/DocumentationAction::getOpenApiDocumentation()` : 

```php
if ('html' === $format) {
    $operation = $operation->withProcessor('api_platform.swagger_ui.processor')->withWrite(true);
}
```
- Updated `src/Symfony/Action/DocumentationAction.php` to check `enable_swagger_ui`, aligning the logic with `src/Laravel/Controller/DocumentationController.php` : 
```diff
- if ('html' === $format) {
+ if ('html' === $format && $this->swaggerUiEnabled) {
    $operation = $operation->withProcessor('api_platform.swagger_ui.processor')->withWrite(true);
}
```

- Added unit & functional tests (using a custom Kernel to handle dynamic configuration) to cover these scenarios.

## Before

```yml
api_platform:
    enable_swagger: true
    enable_swagger_ui: false
```

- `/api/docs` → still HTML Swagger UI accessible (not expected)
- `/api/docs.jsonopenapi` → accessible (expected)

## After

```yml
api_platform:
    enable_swagger: true
    enable_swagger_ui: false
```

- `/api/docs` → returns 404
- `/api/docs.jsonopenapi` → still accessible (expected)

| Route                 | Format | Before     | After          |
|-----------------------|--------|------------|----------------|
| /api/docs             | HTML   | 200 OK (UI Visible) | 404 Not Found  |
| /api/docs.jsonopenapi | JSON   | 200 OK     | 200 OK         |

### CODE REVIEW

**Comment by soyuka** [comment]
would you be able to add a functional test as well?

**Comment by Maxcastel** [comment]
done @soyuka
I will squash commits.

**Comment by soyuka** [comment]
Really nice one thanks!

**Comment by tsiatka** [comment]
I think I've got an issue since this commit

```
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In DefinitionErrorExceptionPass.php line 48:
!!                                                                                 
!!    You have requested a non-existent parameter "api_platform.enable_swagger_ui  
!!    ". Did you mean one of these: "api_platform.enable_entrypoint", "api_platfo  
!!    rm.enable_docs"?   
```

When i'm trying to disable docs in production. I don't know if it's the correct way to do it :

```
when@prod:
    api_platform:
        enable_docs: false
        enable_re_doc: false
        enable_swagger: false
        enable_swagger_ui: false
        enable_entrypoint: false
```

 It was working fine in 4.2.6

File: src/Symfony/Bundle/Resources/config/symfony/controller.php [hunk 1]
```diff
@@ -47,5 +47,6 @@
             service('api_platform.state_processor.main'),
             service('api_platform.negotiator')->nullOnInvalid(),
             '%api_platform.docs_formats%',
+            '%api_platform.enable_swagger_ui%',
```
Comment (ERuban) [inline src/Symfony/Bundle/Resources/config/symfony/controller.php:50]: That addition and similar one below are cause an issue when both `enable_swagger` and `enable_swagger_ui` are false. `api_platform.enable_swagger_ui` parameter isn't registered at that moment

```
You have requested a non-existent parameter "api_platform.enable_swagger_ui". Did you mean one of these: "api_platform.enable_entrypoint", "api_platform.enable_docs"?
