### PR TITLE
fix #3980 TraceableDataPersister supports called without context

### LINKED ISSUE #3980: DataPersister supports called without context
**API Platform version(s) affected**: 2.6.0

**Description**  
After updating to 2.6.0 an error is thrown in data persisters reyling on a specific context property (e.g. item_operation_name) in the supports method. As far as I found out the problem is this code changed which removed the context from the call.
https://github.com/api-platform/core/commit/126e65d8c88f16ee77d8c3cb56da95f7df12171b#diff-fb58705f849532eea1e1b279162e440a919f1ff6cb8509209d3f78dd0c6c65d9R76

**How to reproduce**  
Have a dataPersister supports method check for the item_operation_name without checking first if item_operation_name is set

**Possible Solution**  
Add the context back to the supports call.
Workaround: Always test wether the used array values are actually set

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3980 
| License       | MIT
| Doc PR        | api-platform/docs#...

fix #3980 TraceableDataPersister supports called without context

### CODE REVIEW

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
This must target 2.6 as it's a bug fix.

File: tests/Bridge/Symfony/Bundle/DataPersister/TraceableChainDataPersisterTest.php [hunk 1]
```diff
@@ -60,6 +60,16 @@ public function testRemove($persister, $expected)
...
     }
 
+    public function testSupports() {
+        $context = ['ok' => true];
+        $persister = $this->prophesize(DataPersisterInterface::class);
+        $persister->supports('', $context)->willReturn(true)->shouldBeCalled();
+        $chain = new ChainDataPersister([$persister->reveal()]);
+        $persister->persist('', $context)->shouldBeCalled();
+        $dataPersister = new TraceableChainDataPersister($chain);
+        $dataPersister->persist('',$context);
```
Comment (maks-rafalko) [inline tests/Bridge/Symfony/Bundle/DataPersister/TraceableChainDataPersisterTest.php:70]:
```suggestion
        $dataPersister->persist('', $context);
```

**Review by xammmue — APPROVED** [review]
