### PR TITLE
fix pagination defaults and add tests

### LINKED ISSUE #3992: Bug when using defaults.pagination_enabled to configure pagination
**API Platform version(s) affected**: 2.6.1

**Description**  

Following deprecation recommandation:

https://github.com/api-platform/core/blob/23141d8f80fca56258f3798eec6f7a5a0d4b7cb4/src/Bridge/Symfony/Bundle/DependencyInjection/Configuration.php#L140

If you use the `defaults.pagination_enabled` to configure your pagination (instead of `api_platform.collection.pagination.enabled`) then an error occurs:

`Argument 2 passed to Symfony\Component\DependencyInjection\Extension\Extension::isConfigEnabled() must be of the type array, bool given, called in /var/www/jarvis/vendor/api-platform/core/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php on line 188`

**How to reproduce**  

Configure pagination using `defaults.pagination_enabled`:

```yaml
api_platform:
    defaults:
        pagination_enabled: true
```

**Possible Solution**  

The call to `isConfigEnabled` requires the argument 2 to be an array, not a boolean:

https://github.com/api-platform/core/blob/23141d8f80fca56258f3798eec6f7a5a0d4b7cb4/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L188

This should be:

```php
$container->setParameter('api_platform.collection.pagination.enabled', $config['defaults']['pagination_enabled'] ?? $this->isConfigEnabled($container,  $config['collection']['pagination']));
```

I'm using Symfony `4.4.*` and the signature of `isConfigEnabled` has not changed since 8 years it seems.

### PR DESCRIPTION
**Pull request by GrimpEreau**
| Q             | A
| ------------- | ---
| Bug fix?      | yes 
| New feature?  | no 
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3992 
| License       | MIT
| Doc PR        | n/a

### CODE REVIEW

File: src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php [hunk 1]
```diff
@@ -185,7 +185,7 @@ private function registerCommonConfiguration(ContainerBuilder $container, array
         $container->setParameter('api_platform.collection.exists_parameter_name', $config['collection']['exists_parameter_name']);
         $container->setParameter('api_platform.collection.order', $config['defaults']['order'] ?? $config['collection']['order']);
         $container->setParameter('api_platform.collection.order_parameter_name', $config['collection']['order_parameter_name']);
-        $container->setParameter('api_platform.collection.pagination.enabled', $this->isConfigEnabled($container, $config['defaults']['pagination_enabled'] ?? $config['collection']['pagination']));
+        $container->setParameter('api_platform.collection.pagination.enabled', $config['api_platform']['defaults'] ?? $this->isConfigEnabled($container, $config['collection']['pagination']));
```
Comment (alanpoulain) [inline src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php:188]: I'm not sure this is right. If defaults are set, it will be used for the parameter `api_platform.collection.pagination.enabled`.

Comment (soyuka) [reply src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php:188]: this is correct imo

Comment (alanpoulain) [reply src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php:188]: `$config['api_platform']['defaults']` is not a boolean isn't it?

Comment (soyuka) [reply src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php:188]: it should be `$config['defaults']['pagination_enabled']` indeed, sorry I thought this was the case here

Comment (soyuka) [inline src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php:188]:
```suggestion
        $container->setParameter('api_platform.collection.pagination.enabled', $config['api_platform']['defaults']['pagination_enabled'] ?? $this->isConfigEnabled($container, $config['collection']['pagination']));
```

File: tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php [hunk 2]
```diff
@@ -786,6 +786,22 @@ public function testDisabledSwagger()
...
     }
 
+    public function testPaginationEnabledViaDefaults()
+    {
+        $config = self::DEFAULT_CONFIG;
+        $config['api_platform']['defaults'] = [
+            'attributes' => [
+                'pagination' => true,
+            ],
+        ];
```
Comment (soyuka) [inline tests/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtensionTest.php:796]: It should be:

```
 $config['api_platform']['defaults'] = [
            'pagination_enabled' => true
        ];
```

**Review by soyuka — APPROVED** [review]

**Review by alanpoulain — APPROVED** [review]

**Comment by soyuka** [comment]
thanks @GrimpEreau !
