### PR TITLE
Fix IRI generation with link parameter resources

### LINKED ISSUE #7469: Cannot use new linked resources with using Json LD
**API Platform version(s) affected**: 4.4.2

**Description**  
When using the ReadLinkParameterProvider to automatically load parent DTO as an uriVariable, the serialization encounters issues while trying to generate IRI.

**How to reproduce**  
- Create a DTO that loads another one
```php
<?php

namespace App\ApiResource;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\Link;
use ApiPlatform\State\ParameterProvider\ReadLinkParameterProvider;

#[ApiResource(
    operations: [
        new Get(
            uriTemplate: '/hello/{world}',
            uriVariables: [
                'world' => new Link(fromClass: World::class, provider: ReadLinkParameterProvider::class),
            ],
            provider: HelloWorldProvider::class,
        )
    ]
)]
final readonly class TestResource {
    public function __construct(
        #[ApiProperty(identifier: true)]
        public int $id,
    ) {
    }
}
```

Call `/hello/34` (where 34 is `World` resource identifier value) while accepting `application/ld+json`.
At this point, in my `HelloWorldProvider`, if `World` was found, I have a `World` resource into $operation->getUriVariables()['world'], but $uriVariables['world'] is still `(string) 34`, and I can return whatever value I want from my provider.
If I only accepts `application/json`, everything works fine. But if I accept `application/ld+json`, it goes wild and I get an error from Symfony's UrlGenerator regarding the type of one of the arguments used to generate an IRI.

When rebuilding operation's uriVariables in https://github.com/api-platform/core/blob/main/src/Symfony/Controller/MainController.php#L102 , resource class that was previously injected in operation's uriVariables bag is now passed to $uriVariables which is used for serialization context, but when times come to generate resource's IRI, the resource `world` cannot be used as a value for UrlGenerator.

**Possible Solution**  
When serializing data using https://github.com/api-platform/core/blob/main/src/State/Processor/SerializeProcessor.php#L69 , $uriVariables values that are related to a Link into current Operation should be swapped with their identifier. (Ex: World resource with id 34 should be replaced with 34 instead of the whole object)

**Additional Context**  
Call stack before exception

Image

I found a temporary workaround by adding a `__toString` method to my `World` resource that returns it's identifier as string.

I may provide a PR solving this issue during this week.

### PR DESCRIPTION
**Pull request by Geekimo**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Closes #7469
| License       | MIT

Fixes a bug where link resources using the new ReadLinkParameterProvider fail to generate an IRI when using Hydra.

### CODE REVIEW

File: src/Symfony/Routing/IriConverter.php [hunk 1]
```diff
@@ -183,6 +183,15 @@ private function generateSymfonyRoute(object|string $resource, int $referenceTyp
     {
         $identifiers = $context['uri_variables'] ?? [];
 
+        foreach ($identifiers as $identifier) {
```
Comment (Geekimo) [inline src/Symfony/Routing/IriConverter.php]: At this point, resources loaded with the `ReadLinkParameterProvider` are still objects, so we need to replace them with their identifier's value.

Comment (soyuka) [reply src/Symfony/Routing/IriConverter.php]: we should never reach this path with non scalar identifiers, this is a highly costly path in API Platform imo its inside the identifiers extractor that we should handle this.

Comment (Geekimo) [reply src/Symfony/Routing/IriConverter.php]: @soyuka In the `getIdentifiersFromItem` method, called at line 197 ?

Comment (soyuka) [reply src/Symfony/Routing/IriConverter.php]: probably, I need to take a look not sure what's happening.
