### PR TITLE
fix(validator): fallback to message when detail is uninitialized

### LINKED ISSUE #7843: Upgrade to api-platform 4.3.0: Error: Typed property ValidationException::$detail must not be accessed before initialization
**API Platform version(s) affected**: 4.3.0

**Description**  
In
- https://github.com/api-platform/core/pull/7776
an additional path to convert an Exception to an error was introduced.
But it is possible that the detail property is not initialized.
A check must be put there + a fallback to the previous path where $exception->getMessage() is used for the detail.

Stack trace:
303) App\Tests\Api\ContentNodes\SingleText\CreateSingleTextTest::testCreateRejectsTooLongInstanceName
Error: Typed property ApiPlatform\Validator\Exception\ValidationException::$detail must not be accessed before initialization

/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/validator/Exception/ValidationException.php:167
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/state/ApiResource/Error.php:203
/home/runner/work/ecamp3/ecamp3/api/src/State/ValidationErrorProvider.php:37
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/state/CallableProvider.php:43
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/state/Provider/ReadProvider.php:84
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Security/State/AccessCheckerProvider.php:68
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Bundle/SwaggerUi/SwaggerUiProvider.php:50
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/json-api/State/JsonApiProvider.php:30
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Security/State/AccessCheckerProvider.php:68
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/state/Provider/SecurityParameterProvider.php:50
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/state/Provider/DeserializeProvider.php:60
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Security/State/AccessCheckerProvider.php:68
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Validator/State/ValidateProvider.php:32
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Security/State/AccessCheckerProvider.php:68
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Validator/State/ParameterValidatorProvider.php:101
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/state/Provider/ParameterProvider.php:102
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/state/Provider/ContentNegotiationProvider.php:56
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Controller/MainController.php:94
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/http-kernel/HttpKernel.php:183
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/http-kernel/HttpKernel.php:76
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/http-kernel/EventListener/ErrorListener.php:99
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/EventListener/ExceptionListener.php:50
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/event-dispatcher/Debug/WrappedListener.php:115
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/event-dispatcher/EventDispatcher.php:206
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/event-dispatcher/EventDispatcher.php:56
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php:126
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/http-kernel/HttpKernel.php:241
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/http-kernel/HttpKernel.php:91
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/http-kernel/Kernel.php:193
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/http-kernel/HttpKernelBrowser.php:62
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/framework-bundle/KernelBrowser.php:180
/home/runner/work/ecamp3/ecamp3/api/vendor/symfony/browser-kit/AbstractBrowser.php:398
/home/runner/work/ecamp3/ecamp3/api/vendor/api-platform/symfony/Bundle/Test/Client.php:115
/home/runner/work/ecamp3/ecamp3/api/tests/Api/ECampApiTestCase.php:248
/home/runner/work/ecamp3/ecamp3/api/tests/Api/ContentNodes/CreateContentNodeTestCase.php:237

**How to reproduce**  
Use Error::createFromException with a ValidationException.
https://github.com/ecamp/ecamp3/blob/renovate/api-platform/api/src/State/ValidationErrorProvider.php#L37
PR: https://github.com/ecamp/ecamp3/pull/9231

**Possible Solution**  
A check must be put there + a fallback to the previous path where $exception->getMessage() is used for the detail.

**Additional Context**

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Branch?       | 4.3
| Tickets       | Closes #7843
| License       | MIT
| Doc PR        | ∅

ValidationException::$detail is a typed property with no default, causing an error when getDetail()/getDescription() are called before setDetail(). Fallback to getMessage() which contains the violation list.

### CODE REVIEW

File: src/Validator/Exception/ValidationException.php [hunk 1]
```diff
@@ -164,7 +164,7 @@ public function getTitle(): ?string
 
     public function getDetail(): ?string
     {
-        return $this->detail;
+        return $this->detail ?? $this->getMessage();
```
Comment (BacLuc) [inline src/Validator/Exception/ValidationException.php]: It seems ?? isn't enough.
but it should, according to this:
https://github.com/ecamp/ecamp3/blob/renovate/api-platform/api/src/State/ValidationErrorProvider.php#L38

Here i did an evil hack:
https://github.com/ecamp/ecamp3/blob/renovate/api-platform/api/src/State/ValidationErrorProvider.php#L38

This should not belong in a getter, but maybe in the createFromException method.

Another question is: Why do we create a ValidationException with a non nullable detail property, and don't initialize the detail property?

Comment (BacLuc) [reply src/Validator/Exception/ValidationException.php]: It seems it was added here: https://github.com/api-platform/core/commit/2de5a9bbc55e2008b443c12c64187e4d86d44703#diff-879484ecea95a67561d0849b8b4de9687fc6291cd7476f0b45e77eb4269d4fef

https://github.com/api-platform/core/commit/2de5a9bbc55e2008b443c12c64187e4d86d44703#r179564251

And objects of the type were created in the Normalizer. And setDetail was always called.

This got lost on the way, but ValidationException::getDetail was never called...until now.

Comment (soyuka) [reply src/Validator/Exception/ValidationException.php]: indeed the patch wasn't good, I updated it wdyt?

Comment (BacLuc) [reply src/Validator/Exception/ValidationException.php]: I think for this bug fix it should be good.
In the future one could think about removing the detail property, and returning $this->getMessage() for the getDetail method.

But there is still a path where it doesn't hit the assignments in the constructor.
Maybe an isset($this->detail) in the getter?

Comment (soyuka) [reply src/Validator/Exception/ValidationException.php]: I think we should keep the `detail` property as its part of the JSON Problem spec.
