### PR TITLE
fix: consistent :property placeholder behavior

### LINKED ISSUE #7478: PartialSearchFilter and ExactFilter don't discover property name of filter with `:property` placeholder
**API Platform version(s) affected**: 4.2.2

**Description**  
If I try to use the new `ApiPlatform\Doctrine\Orm\Filter\PartialSearchFilter` or `ApiPlatform\Doctrine\Orm\Filter\ExactFilter` in combination of a `:property` placeholder as the example in the [docs ](https://api-platform.com/docs/core/doctrine-filters/), the filters throw an exception, as the property name is `null`.

If I add one of the filter directly to a parameter, the filter works fine.

**How to reproduce**  
```php
<?php
// api/src/Resource/Book.php

#[ApiResource(operations: [
    new GetCollection(
        parameters: [
            // This WILL restrict to only title and author properties
            'search[:property]' => new QueryParameter(
                properties: ['title', 'author'], // Only these properties get parameters created
                filter: new PartialSearchFilter()
            )
        ]
    )
])]
class Book {
    // ...
}
```

Exception:
```php
ApiPlatform\\Doctrine\\Orm\\Util\\QueryNameGenerator::generateParameterName(): Argument #1 ($name) must be of type string, null given, called in /var/www/html/backend/vendor/api-platform/doctrine-orm/Filter/PartialSearchFilter.php on line 37
```

https://github.com/api-platform/core/blob/main/src/Doctrine/Orm/Filter/PartialSearchFilter.php#L31-L37

**Possible Solution**  
T.B.D.

### PR DESCRIPTION
**Pull request by NathanPesneau**
Completes 

| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Closes #7478
| License       | MIT
| Doc PR        | tbd

This patch introduces a significant internal refactoring to how parameters are processed and applied to filters across API Platform's core, Doctrine, GraphQL, and Laravel integrations. The primary goal is to centralize and solidify parameter handling, particularly for filters that can operate on multiple properties using the `:property` placeholder.

Filters will now receive a more precise context. During the `apply` method, `$context['filters']` will contain only the values directly relevant to the specific filter being processed. This simplifies filter implementation, and developers are encouraged to use `$parameter->getValue()` for direct access to their parameter's associated value.
The `:property` placeholder in parameter keys is now  integrates with the `getProperties()` method of `PropertyAwareFilterInterface` implementations. This resolves previous inconsistencies and solidifies the behavior where `:property` placeholders are dynamically expanded and filled with the content of `getProperties`, ensuring a more predictable and consistent approach for filters that target multiple properties.

This is a **risky change** as it fundamentally alters how certain parameters, especially those using dynamic properties, are processed and how filters receive their values. The previous parameter handling, particularly concerning the interaction between `getProperties` on parameters and dynamic property expansion, was inconsistent and did not work properly in all scenarios. This patch solidifies that behavior.

### CODE REVIEW

File: tests/Functional/Parameters/PartialSearchFilterPlaceholderTest.php [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+namespace ApiPlatform\Tests\Functional\Parameters;
+
+use ApiPlatform\Symfony\Bundle\Test\ApiTestCase;
+use ApiPlatform\Tests\Fixtures\TestBundle\Entity\SuperHero;
+use ApiPlatform\Tests\RecreateSchemaTrait;
+use ApiPlatform\Tests\SetupClassResourcesTrait;
+use PHPUnit\Framework\Attributes\DataProvider;
+
+/**
+ * @author Votre Nom <votre@email.com>
```
Comment (Vinarnt) [inline tests/Functional/Parameters/PartialSearchFilterPlaceholderTest.php]: You need to replace it with your name and email

File: src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php [hunk 2]
```diff
@@ -129,12 +129,16 @@ private function getDefaultParameters(Operation $operation, string $resourceClas
                 $parameters->add($key, $parameter->withProvider($f->getParameterProvider()));
             }
 
-            if (':property' === $key) {
+            if (str_contains($key, ':property')) {
```
Comment (Vinarnt) [inline src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php]: But then the handling of properties aware filters is skipped (see at line 150), by the continue (line 145).

File: tests/Fixtures/TestBundle/Entity/SuperHero.php [hunk 3]
```diff
@@ -0,0 +1,44 @@
...
+
+#[ApiResource(
+    normalizationContext: ['hydra_prefix' => false],
+    parameters: [
+        'search[:property]' => new QueryParameter(
+            filter: new PartialSearchFilter(),
+            properties: ['description', 'name']
+        ),
+    ]
+)]
```
Comment (soyuka) [inline tests/Fixtures/TestBundle/Entity/SuperHero.php]: can you add one to the https://github.com/api-platform/core/blob/main/tests/Fixtures/TestBundle/Entity/SearchFilterParameter.php class?

File: tests/Functional/Parameters/PartialSearchFilterPlaceholderTest.php [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+    /**
+     * @throws \Throwable
+     */
+    protected function setUp(): void
+    {
+        $this->recreateSchema([SuperHero::class]);
+        $this->loadFixtures();
+    }
+
+    #[DataProvider('partialFilterParameterProvider')]
```
Comment (soyuka) [inline tests/Functional/Parameters/PartialSearchFilterPlaceholderTest.php]: please add these tests to the DoctrineTest file

File: src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php (hunk 2 above)
Comment (soyuka) [reply src/Metadata/Resource/Factory/ParameterResourceMetadataCollectionFactory.php]: indeed we should just merge the below branch in this code

```
            if (str_contains($key, ':property') || ((($f = $parameter->getFilter()) && is_a($f, PropertiesAwareInterface::class, true)) || $parameter instanceof PropertiesAwareInterface)) {
                $p = [];
                foreach ($propertyNames as $prop) {
                    $p[$this->nameConverter?->denormalize($prop) ?? $prop] = $prop;
                }
                $parameter = $parameter->withExtraProperties($parameter->getExtraProperties() + ['_properties' => $p]);
            }
 ```
