### PR TITLE
fix(laravel): belongs-to-many relations dont have a get-foreign-key-name method

### LINKED ISSUE #7587: Laravel package bug in ModelMetadata
**API Platform Laravel package version(s) affected**: 4.1.* and 4.2.*

**Description**  
When a Laravel Model has a BelongsToMany relationship, I see this bug: 

ErrorException
vendor/api-platform/laravel/Eloquent/Metadata/ModelMetadata.php:80

array_flip(): Can only flip string and integer values, entry skipped

Laravel version: 12, php version 8.4, api-platform/laravel version 4.1 and 4.2

**Possible Solution**  
In ModelMetadata, on line 80 there is this line:
$foreignKeys = array_flip(array_column($relations, 'foreign_key'));
I've changed it to this line:
$foreignKeys = array_flip(array_filter(array_column($relations, 'foreign_key')));

It looks like API Platform library tries to extract the foreign_key from all relations, but BelongsToMany relations don't have a getForeignKeyName() method, so it returns null. When API Platform tries to flip an array containing null values, PHP throws the error: array_flip(): Can only flip string and integer values, entry skipped.

### PR DESCRIPTION
**Pull request by mariantrifu**
| Q             | A
| ------------- | ---
| Branch?       | 4.2
| Tickets       | Closes #7587 https://github.com/api-platform/core/issues/7587
| License       | MIT

API Platform library tries to extract the foreign_key from all relations, but BelongsToMany relations don't have a getForeignKeyName() method, so it returns null. When API Platform tries to flip an array containing null values, PHP throws the error: array_flip(): Can only flip string and integer values, entry skipped.

### CODE REVIEW

File: src/Laravel/Eloquent/Metadata/ModelMetadata.php [hunk 1]
```diff
@@ -77,7 +77,7 @@ public function getAttributes(Model $model): array
         $indexes = $schema->getIndexes($table);
         $relations = $this->getRelations($model);
 
-        $foreignKeys = array_flip(array_column($relations, 'foreign_key'));
+        $foreignKeys = array_flip(array_filter(array_column($relations, 'foreign_key')));
```
Comment (soyuka) [inline src/Laravel/Eloquent/Metadata/ModelMetadata.php:80]: I'd love to have a functional test for this would you be able to add one? Models are inside `src/Laravel/workbench/app/Models`. 
To run the tests see https://github.com/api-platform/core/blob/4a72073573af0740ffb24c7ed1e8a13e36546654/src/Laravel/CONTRIBUTING.md#tests

Comment (mariantrifu) [reply src/Laravel/Eloquent/Metadata/ModelMetadata.php:80]: Sure, I'll try to add that also.

**Comment by MakFly** [comment]
Hi , i have same problem , when do you think you can merge ? this fix ? 

@soyuka

**Comment by soyuka** [comment]
sure thing is I need to add a test you can also just drop an example of model and request I'll add it (though any llm can do it inside the workbench and the functional tests)
