### PR TITLE
GraphQL: Errors with nullish ManyToOne-Relation when using new ResolverFactory (for version 3.2)

### LINKED ISSUE #6083: GraphQl: Errors with nullish ManyToOne-Relation when using new ResolverFactory
**API Platform version(s) affected**: 3.2

**Description**  
`ItemResolverFactory` and `CollectionResolverFactory` are deprecated and will be removed with 4.0. So I disabled `event_listeners_backward_compatibility_layer` to use the new `ResolverFactory` and see if there are some problems with it. In general this worked fine except for one case. Many-To-One Relations that are allowed to be `null` and are using a custom resolver are behaving different with the new `ResolverFactory`. Formerly the property was just returned as `null` and the resolver got not called. Now the resolver gets called but failes because resolvers are not able to return `null`.

**How to reproduce**  
I created a PR that adds a Behat test for this case.

**Possible Solution**  

**Additional Context**  
I debugged the test case and found the cause, but was not able to fix it properly without breaking other test cases. The checks for already fetched data is different in https://github.com/api-platform/core/blob/main/src/GraphQl/Resolver/Factory/ResolverFactory.php#L36, and https://github.com/api-platform/core/blob/main/src/GraphQl/Resolver/Factory/ItemResolverFactory.php#L48

### PR DESCRIPTION
**Pull request by jotwea**
| Q             | A
| ------------- | ---
| Branch?       | 3.2
| Tickets       | Closes #6083 
| License       | MIT
| Doc PR        | -

This PR introduces a new the test case especially for properties and Many-To-One-Relations being `null`. It fixes the issues relevant for 3.2. There is another PR https://github.com/api-platform/core/pull/6084 that additionally provides a fix for the nested collection feature which was recently introduced on the main branch.

### CODE REVIEW

File: src/GraphQl/Resolver/Factory/ResolverFactory.php [hunk 1]
```diff
@@ -24,20 +25,23 @@ class ResolverFactory implements ResolverFactoryInterface
 {
     public function __construct(
         private readonly ProviderInterface $provider,
-        private readonly ProcessorInterface $processor
+        private readonly ProcessorInterface $processor,
+        private readonly PropertyMetadataFactoryInterface $propertyMetadataFactory
```
Comment (soyuka) [inline src/GraphQl/Resolver/Factory/ResolverFactory.php:29]: this needs to be nullable for backward compatibility

Comment (jotwea) [reply src/GraphQl/Resolver/Factory/ResolverFactory.php]: Done

File: src/GraphQl/Resolver/Factory/ResolverFactory.php [hunk 2]
```diff
@@ -24,20 +25,23 @@ class ResolverFactory implements ResolverFactoryInterface
...
-            // Data already fetched and normalized (field or nested resource)
-            if ($body = $source[$info->fieldName] ?? null) {
-                return $body;
-            }
+            if (\array_key_exists($info->fieldName, $source ?? [])) {
+                $body = $source[$info->fieldName];
 
-            if (null === $resourceClass && \array_key_exists($info->fieldName, $source ?? [])) {
-                return $body;
+                $propertyMetadata = $rootClass ? $this->propertyMetadataFactory?->create($rootClass, $info->fieldName) : null;
```
Comment (soyuka) [inline src/GraphQl/Resolver/Factory/ResolverFactory.php:39]: Do you think that we can use the property metadata from https://github.com/api-platform/core/blob/62263d08c9bfbc50484bd444b33e4c3a8a6bf836/src/GraphQl/Type/FieldsBuilder.php#L356 ? Adding it to the above closure this would prevent from calling the property metadata factory here as this is quite a hot spot.

Comment (jotwea) [reply src/GraphQl/Resolver/Factory/ResolverFactory.php]: yes sure. added it to the closure and dropped it at other place.

File: src/GraphQl/Resolver/Factory/ResolverFactory.php [hunk 3]
```diff
@@ -28,16 +29,18 @@ public function __construct(
...
-                return $body;
-            }
+        return function (?array $source, array $args, $context, ResolveInfo $info) use ($resourceClass, $rootClass, $operation, $propertyMetadataFactory) {
+            if (\array_key_exists($info->fieldName, $source ?? [])) {
+                $body = $source[$info->fieldName];
 
-            if (null === $resourceClass && \array_key_exists($info->fieldName, $source ?? [])) {
-                return $body;
+                $propertyMetadata = $rootClass ? $propertyMetadataFactory?->create($rootClass, $info->fieldName) : null;
+                $propertySchemaType = $propertyMetadata?->getSchema()['type'] ?? null;
```
Comment (soyuka) [inline src/GraphQl/Resolver/Factory/ResolverFactory.php:39]: shouldn't we use `->getBuiltinTypes`?

File: src/GraphQl/Resolver/Factory/ResolverFactory.php [hunk 4]
```diff
@@ -28,16 +29,18 @@ public function __construct(
...
+                // Data already fetched and normalized (field or nested resource)
+                if ($body || null === $resourceClass || $propertyMetadata && 'array' !== $propertySchemaType) {
```
Comment (soyuka) [inline src/GraphQl/Resolver/Factory/ResolverFactory.php:41]:
```suggestion
                if ($body || null === $resourceClass || 'array' !== $propertySchemaType) {
```

File: src/GraphQl/Resolver/Factory/ResolverFactory.php (hunk 3 above)
Comment (jotwea) [reply src/GraphQl/Resolver/Factory/ResolverFactory.php]: changed it. thx

File: src/GraphQl/Resolver/Factory/ResolverFactory.php (hunk 4 above)
Comment (jotwea) [reply src/GraphQl/Resolver/Factory/ResolverFactory.php]: obsolete because `isCollection` of builtInType could have been used.

**Comment by jotwea** [comment]
@soyuka Thx for your latest comments. I updated the PR with the requested changes. The CI still failes for two tests that are not related to my changes. They are already broken on HEAD of 3.2 (https://github.com/api-platform/core/actions/runs/8482337140/job/23241393569). On my local environment they are all passed.

**Comment by soyuka** [comment]
nice thanks! I'll let you now when I merge 3.2 onto main
