### PR TITLE
Fix definition names to be compliant with OpenAPI 3.0 and JSON Point Spec

### LINKED ISSUE #1969: Swagger documentation: Could not resolve reference
When the resource short-name contain a slash the Swagger documentation fail to link the ref and fire error saying "Could not resolve reference ...".

It can be fix by converting every slash by something else (like a -) when generating the definition key in the function getDefinition.

I think this bug was fixed in last version of Swagger UI.

### PR DESCRIPTION
**Pull request by stchr**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | yes
| Deprecations? | no
| Tickets       | fixes #1969
| License       | MIT
| Doc PR        | api-platform/docs#...

Replaces PR #3669 

From https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md#componentsObject
`All the fixed fields declared above are objects that MUST use keys that match the regular expression: ^[a-zA-Z0-9\.\-_]+$.`

Invalid characters will be replaced by `.`. (see https://github.com/api-platform/core/pull/3669#issuecomment-681941187)

### CODE REVIEW

**Review by dunglas — APPROVED** [review]
LGTM!

File: src/JsonSchema/SchemaFactory.php [hunk 1]
```diff
@@ -250,7 +250,12 @@ private function buildDefinitionName(string $className, string $format = 'json',
             $name = $groups ? sprintf('%s-%s', $prefix, implode('_', $groups)) : $prefix;
         }
 
-        return $name;
+        return $this->encodeDefinitionName($name);
+    }
+
+    private function encodeDefinitionName(string $name): string
+    {
+        return preg_replace('/^[a-zA-Z0-9.\-_]+$./', '.', $name);
```
Comment (cziegenberg) [inline src/JsonSchema/SchemaFactory.php:258]: Your commit didn't work for me (tested with a "shortName" set to "directory/sub-directory" - still got the error "Could not resolve reference: #/components/schemas/..."), and I think the problem is the regular expression in that line. I changed it to `preg_replace('/[^a-zA-Z0-9.\-_]+/', '.', $name);` and then it worked for me - but I don't know if this is correct.

Comment (stchr) [reply src/JsonSchema/SchemaFactory.php:258]: @cziegenberg the correct regex should be `preg_replace('/[^a-zA-Z0-9.\-_]/', '.', $name)` in our case.
the additional `+` only says that the definition name must have 1 or more characters. But our use case is only to place INVALID characters.

Comment (stchr) [reply src/JsonSchema/SchemaFactory.php]: @cziegenberg Should be fixed. Can you test?

@dunglas Please review.

**Comment by cziegenberg** [comment]
@stchr I couldn't test it completely, because of other problems with the master branch, but the aforementioned error message doesn't occur anymore.

File: src/JsonSchema/SchemaFactory.php (hunk 1 above)
Comment (cziegenberg) [reply src/JsonSchema/SchemaFactory.php]: @stchr I couldn't test it completely, because of other problems with the master branch, but the aforementioned error message doesn't occur anymore.

**Comment by stchr** [comment]
@dunglas Can be merged IMHO. Thanks!

**Review by dunglas — APPROVED** [review]

**Comment by dunglas** [comment]
Thanks a lot @stchr!
