### PR TITLE
feature: improve ids management for association and fix invalid iri/uuid in SearchFilter

### LINKED ISSUE #775: Bug ? Get collection with filters and several IRI
Hi 

If I call: 

```
GET: votes?decision=/decision/2&creator=/users/1
```

capture d ecran 2016-09-28 a 16 57 28

I got that error: 

```
An exception occurred while executing 'SELECT count(DISTINCT v0_.id) AS sclr_0 FROM vote v0_ INNER JOIN decision d1_ ON v0_.decision_id = d1_.id WHERE d1_.id = ?' with params ["\/decisions\/414&creator=\/users\/43"]:

SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "/decisions/414&creator=/users/43"
```

And the route used is: 
capture d ecran 2016-09-28 a 16 32 52

However, if I do:

```
GET: votes?decision=2&creator=1
```

It's working 
Any idea of why I can't use filters with several IRI ?

### PR DESCRIPTION
**Pull request by Simperfit**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | yes
| Tests pass?   | yes
| Fixed tickets | #775
| License       | MIT
| Doc PR        | 

This PRs update the ids management for association in the SearchFilter.

I've not updated the single at the moment because I think it should be done in another PR. 
This fixes #775.

Something I'm not sure is the behaviour, do we ignore the filter (this is the current implementation) or do we return 0 elements (like by replacing the invalid values with null instead of logging + return) ?

### CODE REVIEW

**Comment by Simperfit** [comment]
@dunglas this needs a review

**Comment by Simperfit** [comment]
@dunglas this needs a review

File: src/Bridge/Doctrine/Orm/Filter/SearchFilter.php [hunk 1]
```diff
@@ -414,4 +434,18 @@ protected function hasValidValues(array $values, $type = null): bool
...
+     * @see regexp taken from https://github.com/ramsey/uuid
+     *
+     * @param string|int $identifier
+     *
+     * @return bool
+     */
+    protected function isValidUuid($identifier): bool
+    {
+        return (bool) preg_match('/^[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}$/', $identifier);
+    }
```
Comment (soyuka) [inline src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: I'm -1 for this. I'd just let the failing doctrine operation throw.

Comment (Toflar) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: Yeah, I agree. Also because you can create your own uuid generator, why would you validate that here?

Comment (Simperfit) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: Then we should not support uuid in here, why are we testing that an int is a valid int then ?

Comment (Toflar) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: Not exactly sure what you mean but to me it should work like this: Whatever I set to be the identifier in doctrine should be searchable and whatever the user is querying on our API, it should not validate the value of the identifier. If doctrine can find an entity based on it it's fine, otherwise not. I don't see why we should validate the value passed by the customer here. Maybe you can elaborate?

Comment (Simperfit) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: The thing is, when passing a non-valid uuid (but according to the type-checking it's valid because it's a valid string) the filter throws an errors 500. 

IMHO checking that you are passing a valid guid when the doctrine metadatas says that should be a guid is the right call, with this, if the guid is not valid, then it will try to search on it, which will lead to the SearchFilter, not filtering which is the expected behaviour.

AFAIK, removing this breaks how we expect filters to work.

Comment (Toflar) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: I have my own id generator:

```
    /**
     * @ORM\Id
     * @ORM\Column(name="voucher", type="string", length=9, options={"fixed":true})
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="App\Doctrine\ORM\EntityManager\VoucherCodeGenerator")
     */
    private $voucher;
```

It's a 9 char, specially generated string. I could not search on that because your UUID validation would fail :(

Comment (Simperfit) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: no, you can, because it's not guid type.
see https://github.com/api-platform/core/pull/1844/files#diff-77ec54980605d6062780fcd93ba31c64R274

Comment (soyuka) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: My believe is that if someone wants a search by uuid he should do it's own because our search filter doesn't support it yet.

As we discussed before, the search filter needs a complete refactor so that it validates most of the needs and it's really hard to do without breaking the so called filter. 
I'd clearly deprecate this class and set up one or two new filters, for example:
- FieldSearchFilter (handles LIKE and such where clauses)
- IdentifierSearchFilter (handles strict equalities, IRIs and everything related to identifiers (`foo.bar=id`). This one would reuse the identifier denormalization introduced a few weeks back).

**Comment by Toflar** [comment]
I really hope this can be released as bugfix because right now, the searchfilter is just completely useless if your identifier column is called `id` 😢

**Comment by Toflar** [comment]
Sure, all my identifiers are uuids and so I named them `uuid` instead of `id` but I could change that.

**Comment by soyuka** [comment]
> Sure, all my identifiers are uuids and so I named them uuid instead of id but I could change that.

IMHO, you should do your own filter to support uuid on identifiers. I agree it'll be closed to a `copy/paste` of the current SearchFilter but I don't think it's a bad idea. It kinda joins the idea I had above (and could maybe be proposed as a new feature for upcoming releases):

> - FieldSearchFilter (handles LIKE and such where clauses)
> - IdentifierSearchFilter (handles strict equalities, IRIs and everything related to identifiers (foo.bar=id). This one would reuse the identifier denormalization introduced a few weeks back).

**Comment by Simperfit** [comment]
I've removed the UUID part.

File: src/Bridge/Doctrine/Orm/Filter/SearchFilter.php [hunk 2]
```diff
@@ -59,16 +60,22 @@ class SearchFilter extends AbstractContextAwareFilter
...
      * @param RequestStack|null $requestStack No prefix to prevent autowiring of this deprecated property
      */
-    public function __construct(ManagerRegistry $managerRegistry, $requestStack = null, IriConverterInterface $iriConverter, PropertyAccessorInterface $propertyAccessor = null, LoggerInterface $logger = null, array $properties = null)
+    public function __construct(ManagerRegistry $managerRegistry, $requestStack = null, IriConverterInterface $iriConverter, PropertyAccessorInterface $propertyAccessor = null, LoggerInterface $logger = null, array $properties = null, IdentifiersExtractorInterface $identifiersExtractor = null)
     {
         parent::__construct($managerRegistry, $requestStack, $logger, $properties);
 
+        if (null === $identifiersExtractor) {
+            @trigger_error('Not injecting ItemIdentifiersExtractor is deprecated since API Platform 2.3 and will not be possible anymore in API Platform 3.0.', E_USER_DEPRECATED);
+        }
```
Comment (soyuka) [inline src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: Shouldn't we say that not having identifiers extractor leads to bugs?

Comment (Simperfit) [reply src/Bridge/Doctrine/Orm/Filter/SearchFilter.php]: It leads to the existing behaviour, we can add it in the message.

**Comment by Simperfit** [comment]
PR rebased with master

File: src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php [hunk 3]
```diff
@@ -448,11 +448,12 @@ private function registerGraphqlConfiguration(ContainerBuilder $container, array
      * @param XmlFileLoader $loader
      * @param bool          $useDoctrine
      */
-    private function registerBundlesConfiguration(array $bundles, array $config, XmlFileLoader $loader, bool $useDoctrine)
+    private function registerBundlesConfiguration(array $bundles, array $config, XmlFileLoader $loader, bool $useDoctrine, ContainerBuilder $container)
     {
         // Doctrine ORM support
         if ($useDoctrine) {
             $loader->load('doctrine_orm.xml');
+            $container->getDefinition('api_platform.doctrine.orm.search_filter')->setArgument('$identifiersExtractor', $container->getDefinition('api_platform.identifiers_extractor.cached'));
```
[the remark this answers is not in the document]
Comment (Simperfit) [reply src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php]: It's the only way I found to be able to have it working it properly and without breaking the order filter. I don't know why it breaks the order filter btw.

[the remark this answers is not in the document]
Comment (meyerbaptiste) [reply src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php]: I don't get it... What is the link between our search filter and our order filter?!

[the remark this answers is not in the document]
Comment (Simperfit) [reply src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php]: I don't know :p! but try it, I've posted a message in slack about this, no one could tell me at the time what was the issue

File: src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml [hunk 4]
```diff
@@ -48,7 +48,6 @@
         </service>
 
         <!-- Filter -->
-
```
Comment (Simperfit) [inline src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml]: to revert

File: src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (meyerbaptiste) [reply src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php]: I mean, `<argument key="$identifiersExtractor" type="service" id="api_platform.identifiers_extractor.cached" />` would be better.
But what worries me is that the user may have bugs when it extends the class and it potentially renames the arguments...

**Comment by soyuka** [comment]
doing this `EU-FOSSA Hackathon`

File: features/doctrine/search_filter.feature [hunk 5]
```diff
@@ -389,8 +462,7 @@ Feature: Search filter on collections
         "@id": {"pattern": "^/dummies$"},
         "@type": {"pattern": "^hydra:Collection$"},
         "hydra:member": {
-          "type": "array",
-          "maxItems": 0
```
[the remark this answers is not in the document]
Comment (soyuka) [reply features/doctrine/search_filter.feature]: This is because the test was wrong in the first place, an invalid filter should not be applied and therefore should return every items of the collection. We fixed that here.

File: tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php [hunk 6]
```diff
@@ -344,15 +345,6 @@ public function provideApplyTestData(): array
                                 ],
                             ],
                         ],
-                        [
-                            '$match' => [
```
[the remark this answers is not in the document]
Comment (soyuka) [reply tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php]: Same reason as above.

File: tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php [hunk 7]
```diff
@@ -469,17 +461,7 @@ public function provideApplyTestData(): array
                     $filterFactory,
                 ],
                 'invalid value for relation' => [
-                    [
-                        [
-                            '$match' => [
```
[the remark this answers is not in the document]
Comment (soyuka) [reply tests/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilterTest.php]: Same reason as above.

File: src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php [hunk 8]
```diff
@@ -40,12 +42,17 @@ final class SearchFilter extends AbstractFilter implements SearchFilterInterface
 
     public const DOCTRINE_INTEGER_TYPE = MongoDbType::INTEGER;
 
-    public function __construct(ManagerRegistry $managerRegistry, IriConverterInterface $iriConverter, PropertyAccessorInterface $propertyAccessor = null, LoggerInterface $logger = null, array $properties = null)
+    public function __construct(ManagerRegistry $managerRegistry, IriConverterInterface $iriConverter, PropertyAccessorInterface $propertyAccessor = null, LoggerInterface $logger = null, array $properties = null, IdentifiersExtractorInterface $identifiersExtractor = null)
     {
         parent::__construct($managerRegistry, $logger, $properties);
 
+        if (null === $identifiersExtractor) {
+            @trigger_error('Not injecting ItemIdentifiersExtractor is deprecated since API Platform 2.5 and can lead to unexpected behaviors, it will not be possible anymore in API Platform 3.0.', E_USER_DEPRECATED);
```
Comment (meyerbaptiste) [inline src/Bridge/Doctrine/MongoDbOdm/Filter/SearchFilter.php]: Mongo is marked as `@experimental`. Not sure BC is relevant here...
