### PR TITLE
Fix #3982 maxDepth property of the ApiSubresource annotation not working

### LINKED ISSUE #3982: @ApiSubresource `maxDepth` parameter is not working in 2.6.1
**API Platform version(s) affected**: 2.6.1

**Description**  

When using the `@ApiSubresource` annotation, routes are still being generated beyond the defined `maxDepth`.

This makes it possible for the "Route pattern" `LogicException` to be thrown by the `RouteCompiler` if an entity shares a subresource of the same type with one of its subresources (i.e. A `Post` has a many-to-one relationship with `Author` and a one-to-many relationship with `Comment` and `Comment` also has a many-to-one relationship with `Author`).

**How to reproduce**  

1. Create Post, Author, and Comment Entities and add the `@ApiSubresource(maxDepth=1)` annotation to all relationships.
   - Post
     - id
     - content
     - author (many-to-one with Author)
     - comments (one-to-many with Post)
   - Author
     - id
     - posts (one-to-many with Post)
     - comments (one-to-many with Comment)
   - Comment
     - id
     - message
     - post (many-to-one with Comment)
     - author (many-to-one with Author)
2. Clear cache to see the "Route pattern" error.

**Additional Context**  

Result of cache:clear with above entities:

```
/srv/api # bin/console cache:clear

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        


In RouteCompiler.php line 149:
                                                                               
  Route pattern "/posts/{id}/author/posts/{posts}/comments/{comments}/author/  
  comments/{comments}/post.{_format}" cannot reference variable name "comment  
  s" more than once.                                                           
                                                                               

cache:clear [--no-warmup] [--no-optional-warmers]
```

Removing the `@ApiSubresource` annotation from `Comment::author` will allow cache to clear, but then you get to see a good example of the subresource depth not being limited:

```
/srv/api # bin/console debug:router | grep "GET"
  api_comments_get_collection                                       GET      ANY      ANY    /comments.{_format}                                                             
  api_comments_get_item                                             GET      ANY      ANY    /comments/{id}.{_format}                                                        
  api_comments_post_get_subresource                                 GET      ANY      ANY    /comments/{id}/post.{_format}                                                   
  api_comments_post_author_get_subresource                          GET      ANY      ANY    /comments/{id}/post/author.{_format}                                            
  api_comments_post_author_posts_get_subresource                    GET      ANY      ANY    /comments/{id}/post/author/posts.{_format}                                      
  api_comments_post_author_posts_comments_get_subresource           GET      ANY      ANY    /comments/{id}/post/author/posts/{posts}/comments.{_format}                     
  api_comments_post_author_comments_get_subresource                 GET      ANY      ANY    /comments/{id}/post/author/comments.{_format}                                   
  api_comments_post_comments_get_subresource                        GET      ANY      ANY    /comments/{id}/post/comments.{_format}                                          
  api_posts_get_collection                                          GET      ANY      ANY    /posts.{_format}                                                                
  api_posts_get_item                                                GET      ANY      ANY    /posts/{id}.{_format}                                                           
  api_posts_author_get_subresource                                  GET      ANY      ANY    /posts/{id}/author.{_format}                                                    
  api_posts_author_posts_get_subresource                            GET      ANY      ANY    /posts/{id}/author/posts.{_format}                                              
  api_posts_author_posts_comments_get_subresource                   GET      ANY      ANY    /posts/{id}/author/posts/{posts}/comments.{_format}                             
  api_posts_author_posts_comments_post_get_subresource              GET      ANY      ANY    /posts/{id}/author/posts/{posts}/comments/{comments}/post.{_format}             
  api_posts_author_comments_get_subresource                         GET      ANY      ANY    /posts/{id}/author/comments.{_format}                                           
  api_posts_author_comments_post_get_subresource                    GET      ANY      ANY    /posts/{id}/author/comments/{comments}/post.{_format}                           
  api_posts_author_comments_post_comments_get_subresource           GET      ANY      ANY    /posts/{id}/author/comments/{comments}/post/comments.{_format}                  
  api_posts_comments_get_subresource                                GET      ANY      ANY    /posts/{id}/comments.{_format}                                                  
  api_posts_comments_post_get_subresource                           GET      ANY      ANY    /posts/{id}/comments/{comments}/post.{_format}                                  
  api_posts_comments_post_author_get_subresource                    GET      ANY      ANY    /posts/{id}/comments/{comments}/post/author.{_format}                           
  api_posts_comments_post_author_posts_get_subresource              GET      ANY      ANY    /posts/{id}/comments/{comments}/post/author/posts.{_format}                     
  api_posts_comments_post_author_comments_get_subresource           GET      ANY      ANY    /posts/{id}/comments/{comments}/post/author/comments.{_format}                  
  api_authors_get_collection                                        GET      ANY      ANY    /authors.{_format}                                                              
  api_authors_get_item                                              GET      ANY      ANY    /authors/{id}.{_format}                                                         
  api_authors_posts_get_subresource                                 GET      ANY      ANY    /authors/{id}/posts.{_format}                                                   
  api_authors_posts_author_get_subresource                          GET      ANY      ANY    /authors/{id}/posts/{posts}/author.{_format}                                    
  api_authors_posts_author_comments_get_subresource                 GET      ANY      ANY    /authors/{id}/posts/{posts}/author/comments.{_format}                           
  api_authors_posts_author_comments_post_get_subresource            GET      ANY      ANY    /authors/{id}/posts/{posts}/author/comments/{comments}/post.{_format}           
  api_authors_posts_author_comments_post_comments_get_subresource   GET      ANY      ANY    /authors/{id}/posts/{posts}/author/comments/{comments}/post/comments.{_format}  
  api_authors_posts_comments_get_subresource                        GET      ANY      ANY    /authors/{id}/posts/{posts}/comments.{_format}                                  
  api_authors_posts_comments_post_get_subresource                   GET      ANY      ANY    /authors/{id}/posts/{posts}/comments/{comments}/post.{_format}                  
  api_authors_posts_comments_post_author_get_subresource            GET      ANY      ANY    /authors/{id}/posts/{posts}/comments/{comments}/post/author.{_format}           
  api_authors_posts_comments_post_author_comments_get_subresource   GET      ANY      ANY    /authors/{id}/posts/{posts}/comments/{comments}/post/author/comments.{_format}  
  api_authors_comments_get_subresource                              GET      ANY      ANY    /authors/{id}/comments.{_format}                                                
  api_authors_comments_post_get_subresource                         GET      ANY      ANY    /authors/{id}/comments/{comments}/post.{_format}                                
  api_authors_comments_post_author_get_subresource                  GET      ANY      ANY    /authors/{id}/comments/{comments}/post/author.{_format}                         
  api_authors_comments_post_author_posts_get_subresource            GET      ANY      ANY    /authors/{id}/comments/{comments}/post/author/posts.{_format}                   
  api_authors_comments_post_author_posts_comments_get_subresource   GET      ANY      ANY    /authors/{id}/comments/{comments}/post/author/posts/{posts}/comments.{_format}  
  api_authors_comments_post_comments_get_subresource                GET      ANY      ANY    /authors/{id}/comments/{comments}/post/comments.{_format}   
```

### PR DESCRIPTION
**Pull request by crbanman**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #3982 
| License       | MIT
| Doc PR        | n/a

- fix the issue with the `maxDepth` parameter of the `ApiSubresource` not working

### CODE REVIEW

**Comment by crbanman** [comment]
fixing...

File: src/Annotation/ApiSubresource.php [hunk 1]
```diff
@@ -20,10 +20,20 @@
...
  * @Annotation
  * @Target({"METHOD", "PROPERTY"})
+ * @Attributes(
+ *     @Attribute("maxDepth", type="int"),
+ * )
  */
 #[\Attribute(\Attribute::TARGET_PROPERTY | \Attribute::TARGET_METHOD)]
 final class ApiSubresource
 {
+    use AttributesHydratorTrait;
```
Comment (crbanman) [inline src/Annotation/ApiSubresource.php:30]: I am wondering if using this trait is unnecessary/overkill.

A simpler solution would be like @rogierknoester suggested in the issue:

```php
public function __construct($maxDepth = null)
{
    if (!\is_array($maxDepth)) { // @phpstan-ignore-line
        $this->maxDepth = $maxDepth;
        return;
    }
    $this->maxDepth = $maxDepth['maxDepth'];
}
```

Comment (soyuka) [reply src/Annotation/ApiSubresource.php:30]: :+1: maxDepth is the only option you can avoid the trait

Comment (crbanman) [reply src/Annotation/ApiSubresource.php:30]: Perfect, I definitely felt like I was getting into code I had no reason to be in. I'll make the changes.

**Review by soyuka — APPROVED** [review]

File: src/Annotation/ApiSubresource.php [hunk 2]
```diff
@@ -36,6 +39,8 @@ public function __construct($maxDepth = null)
     {
         if (!\is_array($maxDepth)) { // @phpstan-ignore-line
```
Comment (alanpoulain) [inline src/Annotation/ApiSubresource.php:40]: Shouldn't we modify the PHPDoc?

Comment (soyuka) [reply src/Annotation/ApiSubresource.php:40]: Not really as we want to keep the auto documentation as we did in https://github.com/api-platform/core/blob/main/src/Annotation/ApiResource.php

**Review by alanpoulain — APPROVED** [review]

**Comment by soyuka** [comment]
thanks @crbanman !
