### PR TITLE
Fix #1224 json-ld context should not be prefixed by #

### LINKED ISSUE #1224: [JSON-LD] Context IRIs are assembled wrong
There is a `#` too much:
```json
"@context": {
  "@vocab": "http://localhost/docs.jsonld#",
  "hydra": "http://www.w3.org/ns/hydra/core#",
  "version": "#Fall/version",
  "erstellungsdatum": "#Fall/erstellungsdatum",
}
```

But it should be:
```json
"@context": {
  "@vocab": "http://localhost/docs.jsonld#",
  "hydra": "http://www.w3.org/ns/hydra/core#",
  "version": "Fall/version",
  "erstellungsdatum": "Fall/erstellungsdatum",
}
```

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #1224
| License       | MIT
| Doc PR        | na

According to the specs I think that the `#` character is there to separate the URL from the given element, for example:

```
    "@context": {
      "name": "http://example.com/organization#name"
    },
```

I'm really no json-ld expert, let me know if removing `#` doesn't seem correct to you.

### CODE REVIEW

File: src/JsonLd/ContextBuilder.php [hunk 1]
```diff
@@ -89,7 +89,7 @@ public function getResourceContext(string $resourceClass, int $referenceType = U
     {
         $context = $this->getBaseContext($referenceType);
         $resourceMetadata = $this->resourceMetadataFactory->create($resourceClass);
-        $prefixedShortName = sprintf('#%s', $resourceMetadata->getShortName());
+        $prefixedShortName = sprintf('%s', $resourceMetadata->getShortName());
```
Comment (meyerbaptiste) [inline src/JsonLd/ContextBuilder.php]: `sprintf` is now useless 😛

Comment (soyuka) [inline src/JsonLd/ContextBuilder.php]: hahaha omg

**Comment by soyuka** [comment]
Thanks @meyerbaptiste 

http://thecodinglove.com/post/126895236416/first-bugfix-on-monday

**Comment by dunglas** [comment]
Please check if our frontend tools still work with this change.

**Comment by soyuka** [comment]
> Please check if our frontend tools still work with this change.

:+1: this is one of my concerns, ping @mysiar

**Comment by soyuka** [comment]
@dunglas I checked in neither `admin` nor `crud-generate` are we using the JSON-LD `/context` endpoint. Something else we'd need to check?

For release-safety I can rebase this on `master` instead of `2.0` and we flag it in the changelog for the next stable. WDYT?

**Comment by dunglas** [comment]
I'm sure we are using it when we normalize the JSON-LD document (the jsonld library used by api-doc-parser does it under the hood).

**Comment by mysiar** [comment]
please check https://www.w3.org/TR/json-ld/#the-context Example 24 and description, it might be relevant

**Comment by soyuka** [comment]
Got it. We should add a test on the [json-ld repository](https://github.com/digitalbazaar/jsonld.js/blob/master/tests/contexts/context-1.jsonld) to see if it's ok.

**Comment by soyuka** [comment]
In fact according to the json-ld tests this patch will work just fine as is closer to the specs. 

Or we may include the api url instead of using relative paths.

**Comment by dunglas** [comment]
Ok let's merge this when the build will be green.

**Comment by soyuka** [comment]
@dunglas tests pass, just appveyor having issues with php not being installed?!

**Comment by meyerbaptiste** [comment]
Try to restart your build, looks like this happens occasionally with chocolatey.org...

**Comment by soyuka** [comment]
:+1: I'm not able to do it I think @dunglas can.

**Comment by meyerbaptiste** [comment]
Force push 😛

**Comment by dunglas** [comment]
Looks good, feel free to merge @soyuka.
