### PR TITLE
[2.5] Fix dashed path segment generation

### LINKED ISSUE #3188: DashPathSegmentNameGenerator not working properly
**API Platform version(s) affected**: 2.4.7

**Description**  
The mentioned class applies Doctrine Inflector's `pluralize` on the whole  resource's name while the method expects a single word, resulting in unexpected output.

For example: when you have an `OrderingPerson` entity added as a resource and use `DashPathSegmentNameGenerator`, the result is `ordering-oeople` instead of `ordering-people`

**How to reproduce**  
1. Create an `OrderingPerson` entity
2. Add it as API Platform resource
3. In `api_platform` configuration section add a `path_segment_name_generator: 'api_platform.path_segment_name_generator.dash'` entry
4. Navigate to endpoints listing, see the result

**Possible Solution**  
Refactor `ApiPlatform\Core\Operation\DashPathSegmentNameGenerator` to treat words from `$name` individually when using `Doctrine\Common\Inflector\Inflector::pluralize`

### PR DESCRIPTION
**Pull request by antograssiot**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fix #3188
| License       | MIT
| Doc PR        | 

This will correctly convert `orderingPerson` to `ordering-people`

### CODE REVIEW

File: tests/Operation/DashedPathSegmentNameGeneratorTest.php [hunk 1]
```diff
@@ -0,0 +1,27 @@
+<?php
```
Comment (soyuka) [inline tests/Operation/DashedPathSegmentNameGeneratorTest.php]: we had no tests for this class? oO

**Comment by teohhanhui** [comment]
Thanks @antograssiot! :tada:
