### PR TITLE
Fix openapi schema sort

### LINKED ISSUE #4047: "ksort() expects parameter 1 to be array, object given" in OpenApiNormizer (empty project)
**API Platform version(s) affected**: 2.6.2

**Description**  & **How to reproduce**

Have:
- PHP 7.4.*
- Symfony CLI installed

Run :
- `composer create-project symfony/skeleton .`
- `composer require api`
- `symfony server:start -d`

Visit:
- `https://127.0.0.1:8000`

image

### PR DESCRIPTION
**Pull request by soyuka**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tickets       | fixes #4047
| License       | MIT
| Doc PR        | na

Fixes schemas sort as it's an ArrayObject not an array.

### CODE REVIEW

File: src/OpenApi/Serializer/OpenApiNormalizer.php [hunk 1]
```diff
@@ -81,6 +79,18 @@ private function recursiveClean($data): array
...
     }
 
+    /**
+     * @param \ArrayObject|array $value
+     */
+    private function ksort(&$value)
+    {
+        if ($value instanceof \ArrayObject) {
+            $value->ksort();
+        } elseif (\is_array($value)) {
```
Comment (alanpoulain) [inline src/OpenApi/Serializer/OpenApiNormalizer.php:89]: Should you use an `elseif`? If it's not an `ArrayObject`, it's an array, according to the PHPDoc.
